# Accroches brutes (typographie appliquée ensuite par genere_accroches.py)
# Format : id -> (texte, allegation) ; allegation = None ou (niveau, nutriment)
A = {
'tomate': ("Gorgée de soleil de juin à septembre. Cuite doucement avec un filet d'huile d'olive et du basilic, comme en Provence.", None),
'concentre_tomate': ("La tomate réduite à son essence. Revenu une minute dans l'huile d'olive, le concentré donne sa profondeur à une sauce ou un tajine.", None),
'carotte': ("Botte fanée au printemps, carotte de garde en hiver. Râpée au citron, ou rôtie au cumin et au miel.", None),
'patate_douce': ("Chair orangée, douce et veloutée. Rôtie avec paprika fumé et citron vert, ou en purée relevée de gingembre.", None),
'epinard': ("Riche en vitamine C quand il est cru, il se croque en pousses dans une salade, ou tombe en une minute à l'ail et à la muscade.", ('riche', 'vitamine_c_mg')),
'chou_frise': ("Feuilles frisées au goût franc de chou. Massées crues à l'huile et au citron, ou grillées au four en chips croustillantes.", None),
'brocoli': ("Bouquets vert profond, à cuire juste croquants. Source de vitamine C, il aime l'ail, le citron et quelques amandes grillées.", ('source', 'vitamine_c_mg')),
'myrtille': ("Petites baies bleu nuit des sous-bois, de juillet à septembre. Sur un yaourt, dans un clafoutis ou simplement à la poignée.", None),
'orange': ("Juteuse et parfumée, reine des étals d'hiver. Riche en vitamine C, en quartiers avec une pointe de cannelle et de fleur d'oranger.", ('riche', 'vitamine_c_mg')),
'kiwi': ("Chair émeraude et acidulée, piquée de graines noires. Riche en vitamine C, il se déguste à la cuillère, coupé en deux.", ('riche', 'vitamine_c_mg')),
'poivron_rouge': ("Charnu et sucré, il se révèle rôti puis pelé, nappé d'huile d'olive. Cru en lanières, il est riche en vitamine C.", ('riche', 'vitamine_c_mg')),
'huile_olive': ("Fruité vert, herbe coupée, pointe poivrée : l'huile vierge extra se goûte crue, sur des légumes, un poisson ou du pain grillé.", None),
'noix': ("Cerneaux au goût boisé, du Périgord ou du Dauphiné. Riches en acides gras oméga-3, ils croquent sur une salade d'endives.", ('riche', 'omega3')),
'amande': ("Croquante, au parfum doux de massepain. Riche en fibres, elle se grille à sec quelques minutes pour révéler tout son goût.", ('riche', 'fibres')),
'graines_lin': ("Graines brunes au goût de céréale grillée, à moudre juste avant usage. Riches en acides gras oméga-3, dans un pain ou un porridge.", ('riche', 'omega3')),
'graines_chia': ("Dans un lait d'amande, elles gonflent en une texture de pudding. Riches en fibres, à marier avec la mangue ou la passion.", ('riche', 'fibres')),
'sardine': ("Confite dans l'huile d'olive, fondante, parfois millésimée. Riche en acides gras oméga-3, sur pain grillé avec un zeste de citron.", ('riche', 'omega3')),
'maquereau': ("Chair franche et soyeuse, pêché au large de la Bretagne au printemps. Grillé à la plancha, avec une moutarde à l'ancienne.", None),
'saumon': ("Chair orangée et fondante, juste nacrée. Riche en acides gras oméga-3, il aime l'aneth, le citron et une croûte de sésame.", ('riche', 'omega3')),
'oeuf': ("Dur, mimosa, brouillé ou en omelette aux fines herbes : l'œuf se prête à tout. Riche en protéines, du matin au soir.", ('riche', 'proteines')),
'lentille': ("Petites et savoureuses, elles cuisent sans trempage. Riches en fibres, tièdes en salade avec échalote, persil et moutarde.", ('riche', 'fibres')),
'pois_chiche': ("Moelleux, au goût de châtaigne. Riches en protéines, rôtis au cumin, en houmous ou dans un couscous aux sept légumes.", ('riche', 'proteines')),
'haricot_rouge': ("Chair tendre et farineuse, la base du chili. Riches en fibres, ils mijotent longuement avec cumin, oignon et tomate.", ('riche', 'fibres')),
'flocons_avoine': ("En porridge crémeux, en granola doré ou en crumble. Riches en fibres, surmontés de fruits de saison et d'une pointe de cannelle.", ('riche', 'fibres')),
'pain_complet': ("Mie dense, croûte bien cuite, arômes de grain. Riche en fibres, grillé avec un beurre demi-sel ou une purée d'amande.", ('riche', 'fibres')),
'the_vert': ("Notes végétales et iodées, du Japon ou de Chine. Infusé à 70 ou 80 °C pendant deux à trois minutes, il garde toute sa douceur.", None),
'chocolat_noir_70': ("Amertume noble, notes de fruits rouges ou de tabac selon l'origine. Un carré laissé fondre lentement, avec un café.", None),
'cacao_poudre': ("Amer et profond, sans sucre. Une cuillère dans un lait chaud, une pâte à crêpes ou un chili, comme au Mexique.", None),
'yaourt_nature': ("Doux et légèrement acidulé. Riche en protéines, avec du miel et des noix, ou en sauce au concombre et à la menthe.", ('riche', 'proteines')),
'kefir': ("Lait fermenté venu du Caucase, frais, acidulé et légèrement pétillant. À boire bien froid, ou en marinade pour un poulet aux épices.", None),
'graines_courge': ("Graines vert jade, torréfiées à sec jusqu'à ce qu'elles chantent dans la poêle. Sur une soupe de potiron ou un taboulé.", None),
'huitre': ("Iodées, de Marennes, d'Arcachon ou de Cancale, les mois d'automne et d'hiver. Nature, avec un trait de citron ou une mignonnette.", None),
'noix_bresil': ("Grosse noix d'Amazonie, crémeuse et fondante. Une ou deux, concassées sur un muesli ou un dessert au chocolat.", None),
'avocat': ("Chair beurrée, presque crémeuse. Mûr quand il cède sous le pouce ; sur pain grillé avec citron vert, piment et fleur de sel.", None),
'eau': ("Fraîche en carafe, avec une rondelle de citron, de concombre ou quelques feuilles de menthe. La boisson de chaque repas.", None),
'fraise': ("Gariguette au printemps, mara des bois en été. Riche en vitamine C, avec quelques feuilles de basilic ou un trait de balsamique.", ('riche', 'vitamine_c_mg')),
'cassis': ("Petite baie noire, intense et acidulée. Riche en vitamine C, en coulis, en sorbet ou en sauce sur un magret.", ('riche', 'vitamine_c_mg')),
'abricot': ("Velouté et doré, du Roussillon ou de la vallée du Rhône, en juin et juillet. Rôti au miel et au romarin, ou nature bien mûr.", None),
'mache': ("Petites rosettes tendres, spécialité nantaise. En salade d'hiver avec betterave, cerneaux et une vinaigrette à l'huile de noix.", None),
'courge_butternut': ("Chair orange au goût de beurre et de noisette. Rôtie au four avec sauge et parmesan, ou en velouté soyeux.", None),
'tofu': ("Caillé de soja délicat, qui prend toutes les saveurs. Riche en protéines, doré à la poêle et laqué de sauce soja et gingembre.", ('riche', 'proteines')),
'pamplemousse': ("Amer et juteux, à la chair rose ou blonde. Riche en vitamine C, en suprêmes dans une salade de crevettes et d'avocat.", ('riche', 'vitamine_c_mg')),
'graines_tournesol': ("Riches en vitamine E, les graines de tournesol se torréfient à sec, puis croquent sur une salade ou un pain maison.", ('riche', 'vitamine_e_mg')),
'noisette': ("Du Piémont ou du Lot-et-Garonne, torréfiée, elle révèle un goût de beurre. Riche en fibres, en praliné maison ou sur une salade.", ('riche', 'fibres')),
'artichaut': ("Feuille à feuille, trempée dans une vinaigrette, jusqu'au fond fondant. Riche en fibres, le camus breton annonce le printemps.", ('riche', 'fibres')),
'asperge': ("Blanches des Landes, vertes de Provence, d'avril à juin. Cuites juste croquantes, avec une sauce mousseline ou un œuf mimosa.", None),
'aubergine': ("Chair soyeuse qui fond à la cuisson. Rôtie entière sur la flamme pour un caviar fumé, ou en parmigiana.", None),
'betterave': ("Chair rubis, sucrée et terrienne. En carpaccio avec du chèvre frais, des noix et un filet de vinaigre de framboise.", None),
'blette': ("Côtes blanches et feuilles vert sombre, deux légumes en un. En gratin, ou en tourte sucrée aux raisins secs, comme à Nice.", None),
'pak_choi': ("Petit chou chinois aux côtes croquantes et aux feuilles tendres. Coupé en deux, saisi au wok avec ail, gingembre et sauce soja.", None),
'celeri_rave': ("Boule noueuse au goût anisé et délicat. En rémoulade à la moutarde, comme dans les bistrots, ou en purée veloutée.", None),
'celeri_branche': ("Croquant, frais, à peine salé. À croquer cru, ou dans le trio oignon, carotte, céleri qui fonde tant de sauces.", None),
'champignon_paris': ("Blanc ou blond, cultivé dans d'anciennes carrières. Cru en fines lamelles au citron, ou poêlé à l'ail et au persil.", None),
'shiitake': ("Chapeau brun au parfum boisé et umami. Saisi au beurre, glissé dans un bouillon de nouilles ou dans un risotto.", None),
'chou_blanc': ("Croquant, doux, légèrement sucré. Émincé très fin en coleslaw, ou fondant dans une potée d'hiver.", None),
'chou_rouge': ("Pourpre profond, qui vire au violet vif avec un trait de vinaigre. Cru en salade aux pommes, ou braisé aux épices.", None),
'chou_vert': ("Feuilles cloquées qui enveloppent une farce, comme en Auvergne. Ou braisé longuement avec des marrons.", None),
'chou_fleur': ("Rôti entier au four, doré et presque sucré. Ou en taboulé cru, râpé en fine semoule avec herbes et citron.", None),
'chou_bruxelles': ("Petites pommes serrées, au goût franc. Coupées en deux et rôties jusqu'à caraméliser, avec un filet de sirop d'érable.", None),
'romanesco': ("Des spirales vertes d'une géométrie parfaite. Cuit à la vapeur, juste croquant, avec un beurre noisette et des câpres.", None),
'concombre': ("Fraîcheur croquante, presque aqueuse. En tzatziki, en raïta ou en fines tranches au vinaigre de riz et au sésame.", None),
'courgette': ("Tendre et délicate, à cueillir petite en été. Crue en tagliatelles au citron, ou en tian provençal avec tomate et thym.", None),
'cresson': ("Feuilles poivrées de cressonnière. Cru, il est riche en vitamine C ; en velouté, il se marie à la pomme de terre.", ('riche', 'vitamine_c_mg')),
'endive': ("Née dans l'obscurité, blanche, croquante et doucement amère. Crue avec noix et roquefort, ou caramélisée à la poêle.", None),
'fenouil': ("Bulbe croquant au parfum d'anis. Cru en fines lamelles à l'orange, ou rôti à l'huile d'olive jusqu'à fondre.", None),
'haricot_vert': ("Fins et croquants, cueillis l'été. Cuits quelques minutes, puis roulés dans un beurre à l'ail et au persil.", None),
'laitue': ("Feuilles tendres et fraîches, la salade de tous les jours. Avec une vinaigrette à la moutarde et des fines herbes du jardin.", None),
'roquette': ("Feuille dentelée au goût poivré, presque piquant. Sur une pizza à la sortie du four, ou avec copeaux de parmesan et poire.", None),
'navet': ("Petits navets nouveaux, sucrés et piquants. Glacés au beurre, en accompagnement d'un canard ou d'un agneau.", None),
'oignon': ("La base de tant de plats. Fondu longuement jusqu'à confire, il devient doux et doré : soupe, tarte ou pissaladière.", None),
'echalote': ("Plus fine et plus parfumée que l'oignon. Ciselée crue dans une vinaigrette, ou rôtie en chemise jusqu'à confire.", None),
'poireau': ("Tiède en vinaigrette comme dans les bistrots, fondu dans une flamiche picarde ou une soupe aux pommes de terre.", None),
'petits_pois': ("Doux et sucrés, à écosser en mai et juin. À la française, avec laitue et oignons nouveaux, ou en velouté à la menthe.", None),
'feve': ("Fèves de printemps, à double écosser pour révéler leur vert vif. En purée à l'huile d'olive, comme dans les Pouilles.", None),
'potiron': ("Chair orange et fondante, symbole de l'automne. En velouté à la muscade, en gratin ou en tarte à la cannelle.", None),
'potimarron': ("Se cuisine avec son écorce, au goût de châtaigne. En quartiers rôtis au thym, ou en velouté au lait de coco.", None),
'radis': ("Croquant et piquant, rose et blanc. À la française : avec du beurre, du sel et une tranche de pain de campagne.", None),
'radis_noir': ("Chair blanche et ferme au piquant prononcé. Râpé en rémoulade, ou en fines lamelles avec du sel et du fromage frais.", None),
'panais': ("Racine ivoire, oubliée puis retrouvée, sucrée et anisée. Rôti au miel, ou en purée parfumée d'une pointe de muscade.", None),
'topinambour': ("Tubercule au goût d'artichaut. En velouté soyeux, ou rôti en fines chips croustillantes avec du thym.", None),
'salsifis': ("Racine fine, légume oublié au goût délicat d'asperge. Poêlé au beurre et au persil, ou en gratin.", None),
'gombo': ("Gousses vertes fondantes, stars du gumbo de Louisiane et des sauces d'Afrique de l'Ouest. À saisir entières, à feu vif.", None),
'mais_doux': ("Grains sucrés et croquants. Grillés à la poêle avec citron vert et piment, en salade ou dans une galette.", None),
'poivron_jaune': ("Le plus doux des poivrons, charnu et fruité. En peperonata avec oignon et tomate, ou cru en bâtonnets avec un houmous.", None),
'tomate_cerise': ("Petites bouchées sucrées, rouges, jaunes ou noires. Rôties en grappe avec thym et huile d'olive, ou croquées telles quelles.", None),
'pomme_de_terre': ("Charlotte, ratte, bintje : une variété pour chaque plat. Vapeur avec un filet d'huile d'olive, ou en écrasée aux herbes.", None),
'manioc': ("Racine ferme au goût doux, d'Afrique et d'Amérique latine. Toujours bien cuite, puis dorée à la poêle ou en frites.", None),
'igname': ("Tubercule à la chair ferme et farineuse, des marchés africains et antillais. Bouillie puis pilée, ou en ragoût épicé.", None),
'banane_plantain': ("Mûre et noire, elle caramélise en alloco ; verte et ferme, elle se frit en tostones croustillants.", None),
'nori': ("Feuille d'algue grillée au goût iodé et fumé. Pour rouler les makis, ou émiettée sur un bol de riz.", None),
'wakame': ("Algue au goût marin délicat. Trempée quelques minutes, puis glissée dans une soupe miso ou une salade au sésame et au vinaigre de riz.", None),
'pomme': ("Croquante, acidulée ou sucrée, du verger français. Crue avec du fromage, en tarte fine ou en compote à la cannelle.", None),
'poire': ("Juteuse et fondante quand elle est mûre à point. Pochée à la vanille, avec un bleu, ou en carpaccio avec des noix.", None),
'cerise': ("Burlat, bigarreau, griotte : le goût de juin. En clafoutis, comme dans le Limousin, ou croquées à même la branche.", None),
'prune': ("Juteuse et sucrée à la fin de l'été. Rôtie au four avec un peu de miel, ou en tarte sur une pâte fine.", None),
'mirabelle_reine_claude': ("Dorée ou verte, juteuse et parfumée, en août et septembre. En tarte, en confiture, ou simplement cueillie sur l'arbre.", None),
'peche': ("Blanche ou jaune, veloutée et parfumée en plein été. Rôtie à la verveine, ou crue avec une mozzarella et du basilic.", None),
'nectarine': ("Lisse et juteuse, au parfum de pêche. En tranches avec une burrata et de la menthe, ou grillée au miel.", None),
'raisin': ("Muscat, chasselas, italia : les grappes sucrées de l'automne. Sur un plateau de fromages, ou rôti avec une volaille.", None),
'figue': ("Chair pourpre et mielleuse, comme la violette de Solliès, en fin d'été. Rôtie au thym, ou crue avec du chèvre frais.", None),
'melon': ("Charentais au parfum intense : choisissez-le lourd, le pédoncule prêt à se détacher. Bien frais, avec quelques feuilles de menthe.", None),
'pasteque': ("Chair rose et croquante, gorgée d'eau. En cubes avec feta et menthe, comme en Grèce, ou en granité.", None),
'framboise': ("Délicate et parfumée, fruit de l'été. Source de fibres, sur une tarte sablée ou écrasée dans un yaourt.", ('source', 'fibres')),
'groseille': ("Grappes translucides, rouges et acidulées. En gelée, sur une pavlova, ou en touche vive sur un gibier.", None),
'mure': ("Baie noire des haies de fin d'été. Écrasée dans un crumble ou réduite en coulis, elle est source de fibres.", ('source', 'fibres')),
'rhubarbe': ("Tiges acidulées, roses ou vertes, du printemps. En compote avec des fraises, ou en crumble sous une pâte beurrée.", None),
'coing': ("Fruit dur et parfumé, qui rosit à la cuisson. En pâte de coing avec un fromage de brebis, ou poché à la vanille.", None),
'citron': ("Le zeste pour le parfum, le jus pour la vivacité. Sur un poisson, une salade, un gâteau, ou confit au sel à la marocaine.", None),
'citron_vert': ("Plus vif et plus parfumé que le citron jaune. Pour un ceviche, un guacamole ou un curry thaï.", None),
'clementine': ("Choisie avec ses feuilles, signe de fraîcheur, comme en Corse. Riche en vitamine C, en quartiers ou pressée au petit-déjeuner.", ('riche', 'vitamine_c_mg')),
'banane': ("Douce et crémeuse. Écrasée dans une pâte à pancakes, rôtie à la cannelle ou tranchée sur un porridge.", None),
'mangue': ("Chair fondante et parfumée, orange vif. En lassi, ou en salsa avec citron vert et coriandre sur un poisson grillé.", None),
'papaye': ("Chair corail, douce et fondante. Arrosée de citron vert, ou verte et râpée en som tam, la salade thaïe.", None),
'ananas': ("Juteux, sucré, acidulé. Rôti à la vanille et au poivre de Sichuan, ou frais en carpaccio avec de la menthe.", None),
'goyave': ("Parfum tropical intense, entre poire et fraise. Riche en vitamine C, en jus, en pâte de goyave ou avec un fromage frais.", ('riche', 'vitamine_c_mg')),
'fruit_passion': ("Pulpe acidulée et parfumée, pleine de graines croquantes. À la cuillère, sur une pavlova ou dans une vinaigrette.", None),
'litchi': ("Chair nacrée au parfum de rose, de décembre à février. Pelé bien frais, ou en salade avec framboises et menthe.", None),
'kaki': ("Mûr, il se déguste à la cuillère comme une confiture. Ferme, en lamelles dans une salade avec grenade et roquette.", None),
'grenade': ("Des grains rubis qui craquent sous la dent, entre acidité et douceur. En finition d'un taboulé ou d'un houmous, comme au Levant.", None),
'figue_barbarie': ("Fruit du cactus, à la chair rose et parfumée. À peler avec des gants, puis à déguster frais avec un trait de citron vert.", None),
'kumquat': ("Petit agrume qui se croque entier : écorce sucrée, pulpe acidulée. Confit au sirop, ou en rondelles dans une salade.", None),
'olive': ("Verte et ferme ou noire et fondante, de Lucques ou de Nyons. Marinée à l'ail et au citron, ou dans une tapenade.", None),
'chataigne': ("Fruit des forêts d'Ardèche et de Corse. Grillée au feu de bois en automne, ou en velouté avec des champignons.", None),
'datte': ("Moelleuse et mielleuse, Medjool ou Deglet Nour. Fourrée d'une amande, ou fondue dans un tajine d'agneau.", None),
'figue_seche': ("Moelleuse et granuleuse, au goût de miel. Riche en fibres, avec un fromage de brebis ou dans un pain aux noix.", ('riche', 'fibres')),
'pruneau': ("Le pruneau d'Agen, séché lentement, aux notes de caramel. Dans un tajine, un far breton ou fourré d'un cerneau de noix.", None),
'raisin_sec': ("Sultanine blonde ou Corinthe noire. Gonflé dans un thé, il se glisse dans un couscous, un pilaf ou un pain aux céréales.", None),
'abricot_sec': ("Orange profond, moelleux et acidulé. Riche en fibres, dans un tajine, une farce ou simplement avec des amandes.", ('riche', 'fibres')),
'lentille_verte_puy': ("Lentille AOP des sols volcaniques de Haute-Loire. Riche en protéines, elle reste ferme et goûteuse en salade tiède.", ('riche', 'proteines')),
'lentille_corail': ("Elle fond en quinze minutes en une purée dorée : dal indien au curcuma, ou soupe turque au citron et au cumin.", None),
'pois_casse': ("Riches en fibres, ils fondent en soupe veloutée, ou en fava grecque à l'huile d'olive et aux câpres.", ('riche', 'fibres')),
'haricot_blanc': ("Lingot du Nord ou coco de Paimpol, tendre et fondant. En salade à l'huile d'olive et à la sauge, ou dans un cassoulet.", None),
'flageolet': ("Petit haricot vert pâle, compagnon du gigot d'agneau. Riche en fibres, mijoté avec thym, ail et laurier.", ('riche', 'fibres')),
'haricot_mungo': ("Petits grains verts d'Asie : ce sont leurs germes que l'on appelle pousses de soja. En dal, ou en soupe sucrée à la vietnamienne.", None),
'houmous': ("Pois chiches, tahin, citron et ail, à la mode du Levant. Avec un filet d'huile d'olive, du paprika et un pain pita chaud.", None),
'tempeh': ("Galette de soja fermenté venue de Java, aux notes de champignon. Riche en protéines, dorée à la poêle avec ail et sauce soja.", ('riche', 'proteines')),
'miso': ("Pâte de soja fermentée, pilier de la cuisine japonaise. Dans un bouillon, ou en glaçage sur une aubergine rôtie, pour sa note umami.", None),
'tofu_soyeux': ("Texture de flan, fondante et délicate. En dessert à la vanille, mixé en sauce crémeuse ou en cubes dans une soupe miso.", None),
'boisson_soja_calcium': ("Douce, au léger goût de fève. Dans un café, un porridge ou une pâte à crêpes.", None),
'riz_complet': ("Grain entier au goût de noisette et à la mâche ferme. En bol avec des légumes rôtis, ou sauté aux œufs et à la ciboule.", None),
'riz_basmati': ("Grain long et parfumé, des contreforts de l'Himalaya. Rincé puis cuit à l'étouffée, pour des grains bien séparés.", None),
'sarrasin': ("Graines triangulaires au goût grillé, la kacha d'Europe de l'Est. Riche en fibres, torréfié puis cuit comme un risotto.", ('riche', 'fibres')),
'galette_sarrasin': ("La galette bretonne, dentelle brune et croustillante. Complète avec œuf, comté et champignons, ou nature au beurre salé.", None),
'quinoa': ("Graines des Andes, à rincer avant cuisson. Source de protéines, en salade avec avocat, grenade et herbes fraîches.", ('source', 'proteines')),
'boulgour': ("Blé concassé, la base du taboulé libanais, avec persil et menthe à profusion. Ou en pilaf aux tomates.", None),
'orge_perlee': ("Grains ronds et moelleux. En orzotto crémeux aux champignons, ou dans une soupe écossaise aux légumes d'hiver.", None),
'epeautre': ("Céréale ancienne cultivée en Haute-Provence. Riche en fibres, en salade, ou dans la soupe d'épeautre à l'agneau.", ('riche', 'fibres')),
'millet': ("Petites graines dorées au goût doux. Cuit comme une semoule, en galettes de légumes ou en porridge au lait d'amande.", None),
'pates_completes': ("Pâtes au blé complet, au goût rustique de céréale. Al dente avec des brocolis, de l'ail et un peu de piment.", None),
'pain_seigle': ("Mie dense et brune, légèrement acidulée. En tartine avec saumon fumé et aneth, à la nordique, ou avec des huîtres.", None),
'couscous': ("Semoule dorée, gonflée à la vapeur et égrenée à la main. Avec un bouillon aux sept légumes et du ras-el-hanout.", None),
'polenta': ("Semoule de maïs dorée d'Italie du Nord. Crémeuse au parmesan, ou refroidie, taillée et grillée.", None),
'tortilla_mais': ("Galette de maïs du Mexique, souple et parfumée. Chauffée à la poêle, garnie de haricots, d'avocat et de salsa.", None),
'vermicelle_riz': ("Fils translucides de riz, à tremper quelques minutes dans l'eau chaude. Pour les rouleaux de printemps, un bo bun ou un pho.", None),
'son_avoine': ("L'enveloppe du grain d'avoine, au goût doux. Riche en fibres, dans un porridge, un yaourt ou une pâte à muffins.", ('riche', 'fibres')),
'pistache': ("Verte et parfumée, de Sicile ou d'Iran. Concassée sur un tajine, une burrata, ou en pâte pour les desserts.", None),
'noix_cajou': ("Tendre et beurrée une fois torréfiée. Dans un curry, un sauté au wok, ou mixée en crème végétale.", None),
'noix_pecan': ("Cousine américaine de la noix, aux notes d'érable. Riche en fibres, caramélisée sur une tarte ou une salade de courge.", ('riche', 'fibres')),
'macadamia': ("Ronde et fondante, la plus beurrée des noix, d'Australie ou d'Hawaï. Dans un cookie, ou concassée sur une salade tropicale.", None),
'cacahuete': ("Torréfiée, croquante et gourmande. Concassée sur un pad thaï, ou mijotée dans un mafé, le ragoût d'Afrique de l'Ouest.", None),
'beurre_cacahuete': ("Pâte d'arachide onctueuse, pilier du mafé sénégalais. Sur une tartine avec de la banane, ou dans une sauce saté.", None),
'pignon': ("Graine du pin parasol, tendre et résineuse. Dorée à sec pour un pesto, un taboulé ou des épinards à la catalane.", None),
'sesame': ("Graines blondes ou noires, au goût grillé. Sur un pain, un poisson laqué ou un bol de nouilles froides.", None),
'tahin': ("Purée de sésame onctueuse et légèrement amère. Pour le houmous, une sauce au citron sur des légumes rôtis, ou une halva.", None),
'noix_coco_rapee': ("Chair de coco séchée au parfum tropical. Dans un granola, des rochers à la coco ou un curry de légumes.", None),
'huile_colza': ("Huile douce aux notes végétales, née des champs jaunes du printemps. Riche en acides gras oméga-3, en vinaigrette ou en mayonnaise.", ('riche', 'omega3')),
'huile_noix': ("Au parfum intense de cerneau grillé. Riche en acides gras oméga-3, quelques gouttes sur une mâche, des endives ou des lentilles.", ('riche', 'omega3')),
'hareng': ("Poisson des mers du Nord à la chair fine. Grillé, il est riche en acides gras oméga-3 ; avec pommes de terre tièdes et oignon rouge.", ('riche', 'omega3')),
'anchois': ("Filets fondants de Collioure ou de Cantabrie. Sur une pizza, dans une tapenade, ou fondus dans une sauce aux câpres.", None),
'truite': ("Chair rose et délicate. À la meunière, avec des amandes effilées et un beurre noisette.", None),
'cabillaud': ("Chair blanche en beaux feuillets nacrés. Riche en protéines, rôti sous une croûte d'herbes ou servi avec un aïoli.", ('riche', 'proteines')),
'lieu_noir': ("Chair ferme et savoureuse, pêché en Atlantique Nord. Poêlé avec une sauce vierge, ou en parmentier aux herbes.", None),
'merlan': ("Chair fine et fondante, à cuire avec délicatesse. En papillote avec citron, fenouil et un filet d'huile d'olive.", None),
'dorade': ("La dorade royale, reconnaissable à son sourcil doré. Rôtie entière au four avec citron, fenouil et thym.", None),
'bar': ("Chair fine et ferme, prisée des grands chefs. En croûte de sel pour une cuisson parfaite, ou poêlé avec une huile au basilic.", None),
'thon_naturel': ("Prêt à l'emploi, ferme et pratique. En salade niçoise, en rillettes au citron, ou dans un pan bagnat.", None),
'moule': ("De bouchot ou de corde, de Bretagne ou de Méditerranée. À la crème, au curry ou au safran, avec des frites comme en Belgique.", None),
'crevette': ("Rose, sucrée et ferme. Sautée à l'ail et au piment, dans un curry vert, ou en cocktail avec un avocat.", None),
'calamar': ("Tendre quand il est saisi à feu vif ou mijoté longtemps. À la plancha avec ail et persil, ou farci à la sétoise.", None),
'poulpe': ("Cuit longuement jusqu'à fondre, puis tranché avec pommes de terre, paprika et huile d'olive, à la galicienne.", None),
'saint_jacques': ("Noix nacrées et sucrées, pêchées d'octobre à mai. Snackées une minute par face, arrosées d'un beurre noisette.", None),
'palourde': ("Petit coquillage à la chair ferme et iodée. En spaghetti alle vongole, avec ail, persil et huile d'olive.", None),
'poulet': ("Riche en protéines, le filet se marine au citron et aux herbes, puis se grille ou se poche dans un bouillon au gingembre.", ('riche', 'proteines')),
'dinde': ("Escalope fine et tendre, à saisir vite. Panée aux herbes, à la crème de moutarde, ou émincée au wok.", None),
'lapin': ("Chair fine, un classique de la table française. À la moutarde, aux pruneaux, ou à la provençale avec olives et thym.", None),
'boeuf_maigre': ("Steak grillé à point, reposé quelques minutes. Avec une sauce au poivre, des herbes ou un beurre à l'échalote.", None),
'agneau': ("Gigot rosé, piqué d'ail et de romarin, rôti au four. Avec des flageolets, pour le déjeuner de Pâques.", None),
'porc_filet': ("Filet mignon tendre et juteux. Rôti aux pruneaux, laqué au miel et au soja, ou en médaillons à la moutarde.", None),
'yaourt_grec': ("Épais et onctueux comme une crème. Avec du miel de thym et des noix, ou en sauce à l'ail et à l'aneth pour un agneau grillé.", None),
'fromage_blanc': ("Onctueux et frais, un classique du dessert à la française. Riche en protéines, avec un coulis de fruits rouges ou des fines herbes.", ('riche', 'proteines')),
'lait_demi_ecreme': ("Le lait de tous les jours, doux et polyvalent. Dans un chocolat chaud, une béchamel ou un riz au lait vanillé.", None),
'chevre_frais': ("Frais, doux et légèrement acidulé. Sur une tartine au miel et au thym, ou émietté dans une salade de lentilles.", None),
'feta': ("Fromage de brebis grec, salé et friable, affiné en saumure. En salade grecque, ou rôtie au four avec tomates et origan.", None),
'parmesan': ("Affiné de longs mois, aux cristaux croquants. En copeaux sur une roquette, ou râpé sur des pâtes au dernier moment.", None),
'comte': ("Fromage AOP du massif du Jura, affiné quatre mois au moins. Notes de noisette et de beurre, en lamelles ou fondu.", None),
'mozzarella': ("Pâte filée blanche et fondante. Avec tomates mûres, basilic et huile d'olive, ou fondue sur une pizza napolitaine.", None),
'ricotta': ("Douce et crémeuse, née du petit-lait. Dans des raviolis aux épinards, un cheesecake ou sur une tartine au miel.", None),
'brebis_pyrenees': ("Pâte ferme au goût de lait de brebis et de noisette. Avec une confiture de cerises noires, à la basque.", None),
'curcuma': ("L'épice d'or des currys indiens. Chauffée dans un filet d'huile, elle se marie au poivre noir, au cumin et au gingembre.", None),
'gingembre': ("Frais, piquant et citronné. Râpé dans un sauté au wok, une marinade de poisson ou un sirop pour salade de fruits.", None),
'cannelle': ("Écorce roulée au parfum chaud et sucré, de Ceylan ou de Chine. Sur une compote de pommes, un riz au lait ou un tajine.", None),
'cumin': ("Graines au parfum chaud et terreux. Torréfiées à sec, elles relèvent carottes rôties, houmous, chili et currys.", None),
'paprika': ("Piment doux en poudre, rouge profond. Fumé à l'espagnole ou doux de Hongrie, dans un goulash ou sur des œufs brouillés.", None),
'poivre_noir': ("Le roi des épices, de Kampot ou du Malabar. Toujours moulu à la dernière minute, pour tout son parfum.", None),
'piment': ("Frais, vert ou rouge, il apporte le feu. À épépiner pour l'adoucir, dans une salsa, un curry ou une huile pimentée.", None),
'cardamome': ("Gousses vertes au parfum frais et camphré. Dans un chai, un riz biryani ou une brioche suédoise.", None),
'safran': ("L'épice la plus précieuse, cueillie stigmate par stigmate. Infusé dans l'eau tiède, pour une paella, une bouillabaisse ou un risotto.", None),
'ail': ("Rose de Lautrec, blanc de Lomagne ou violet de Cadours. Confit au four, il devient doux comme une crème.", None),
'persil': ("Plat ou frisé, l'herbe de la persillade. Haché à la dernière minute avec de l'ail, sur des pommes de terre ou des champignons.", None),
'coriandre': ("Feuilles fraîches aux notes d'agrumes. Dans un pho, un guacamole ou une chermoula, ajoutée au dernier moment.", None),
'menthe': ("Fraîche et vive, l'herbe du thé à la menthe et du taboulé. Avec des petits pois, une salade de pastèque ou un agneau.", None),
'basilic': ("Parfum solaire, grand vert de Gênes ou basilic thaï. Dans un pesto, sur une tomate-mozzarella ou dans un curry vert.", None),
'aneth': ("Herbe fine et anisée du Nord. Avec un saumon gravlax, des pommes de terre nouvelles ou un concombre à la crème.", None),
'ciboulette': ("Fines tiges au goût d'oignon doux. Ciselée aux ciseaux sur une omelette, une pomme de terre ou un fromage blanc.", None),
'thym': ("L'herbe des garrigues. Frais ou séché, sur un agneau, des légumes rôtis ou une ratatouille.", None),
'romarin': ("Aiguilles résineuses aux notes de pin. Sur des pommes de terre rôties, un carré d'agneau ou une focaccia.", None),
'origan': ("Séché, il gagne en parfum. L'herbe de la pizza, de la salade grecque et des sauces tomate du Sud.", None),
'vanille': ("Gousse de Madagascar ou de Tahiti, fendue et grattée. Dans une crème brûlée, un riz au lait ou avec des fraises.", None),
'choucroute': ("Chou fermenté d'Alsace, acidulé et fondant. Avec un haddock poché et quelques baies de genièvre, en version de la mer.", None),
'miel': ("Lavande, acacia ou châtaignier : chaque fleur son parfum. Sur un fromage frais, dans une vinaigrette ou un thé.", None),
'sirop_erable': ("Sève d'érable du Québec, réduite lentement jusqu'à l'ambre. Sur des pancakes, ou pour glacer des carottes ou un saumon.", None),
'rutabaga': ("Racine jaune au goût doux, entre navet et chou. En purée au beurre, à la scandinave, ou rôti en frites au four.", None),
'chou_rave': ("Boule croquante au goût de brocoli doux. Crue en bâtonnets ou en rémoulade, ou poêlée au beurre.", None),
'courge_musquee': ("Grosse courge de Provence à la chair orange et musquée. En gratin, en soupe au lait de coco ou en tarte sucrée.", None),
'haricot_beurre': ("Jaune pâle et fondant. Tiède avec des herbes fraîches, ou en salade avec tomates et échalote.", None),
'sucrine': ("Petite laitue craquante et douce. Coupée en quatre et grillée à la poêle, ou crue avec une vinaigrette aux anchois.", None),
'laitue_romaine': ("Feuilles longues et craquantes, reines de la salade César. Ou en barquettes garnies de crevettes et d'avocat.", None),
'chicoree_frisee': ("Feuilles fines et doucement amères. Avec des croûtons aillés, des noix et une vinaigrette bien moutardée.", None),
'oignon_rouge': ("Doux et croquant, d'un beau pourpre. Cru dans une salade, ou en pickles minute au vinaigre.", None),
'poivron_vert': ("Le plus vif des poivrons, légèrement amer. Dans une piperade basque, un chili ou farci.", None),
'courge_spaghetti': ("Sa chair se détache en filaments comme des spaghettis. Cuite au four, puis servie avec sauce tomate et parmesan.", None),
'taro': ("Tubercule farineux au goût de châtaigne. Toujours bien cuit, en ragoût, en frites, ou en dessert au lait de coco.", None),
'christophine': ("La chayote des Antilles, douce et croquante. Gratinée, farcie à la créole, ou crue en fines lamelles.", None),
'riz_sauvage': ("Graine noire et élancée des lacs d'Amérique du Nord, au goût fumé. Mêlée à un riz basmati, ou en salade d'automne.", None),
'lentille_blonde': ("Blonde et fondante, au goût délicat. En potage, en salade tiède ou en purée avec une échalote confite.", None),
'farine_complete': ("Farine de blé entier, au goût de grain. Pour les pains, les crêpes, les crumbles et les pâtes à tarte.", None),
'pain_pita': ("Pain plat du Levant, qui gonfle en poche à la cuisson. Garni de falafels, de légumes et de tahin, ou grillé en chips.", None),
'eglefin': ("Cousin du cabillaud à la chair fine ; fumé, il devient haddock. À la vapeur, avec un beurre blanc à la ciboulette.", None),
'lotte': ("Chair ferme et sans arête, souvent comparée au homard. En gigot rôti, en blanquette, ou au paprika et à l'huile d'olive.", None),
'rouget': ("Robe rouge et chair fine au goût de roche. Poêlé une minute, avec une tapenade, ou dans une soupe de poissons.", None),
'tourteau': ("Crabe de Bretagne à la chair blanche et douce. Décortiqué patiemment, avec une mayonnaise maison et du pain de seigle.", None),
'bulot': ("Coquillage de la Manche, emblème de Granville. Cuit au court-bouillon, servi tiède avec une mayonnaise.", None),
'veau_escalope': ("Escalope tendre et fine. À la milanaise, en piccata au citron, ou à la crème et aux champignons.", None),
'yaourt_brebis': ("Plus crémeux et plus doux que le yaourt de vache. Avec une confiture de figues, ou du miel et des pistaches.", None),
'boisson_amande': ("Boisson végétale au goût doux d'amande. Dans un porridge, un café ou un pudding de chia.", None),
'tisane': ("Verveine, camomille, tilleul ou menthe : une tasse chaude, infusée cinq minutes. Avec une rondelle de citron ou un peu de miel.", None),
'the_noir': ("Darjeeling, Assam ou Ceylan : des notes maltées ou fruitées. Infusé trois à quatre minutes, nature ou avec un nuage de lait.", None),
'jus_orange': ("Pressé minute, juteux et parfumé. Un verre au petit-déjeuner, ou réduit en sauce pour un canard à l'orange.", None),
'moutarde': ("La forte de Dijon ou l'ancienne à grains. Dans une vinaigrette, sur un lapin ou pour relever une sauce.", None),
'sauce_soja': ("Soja et blé fermentés longuement. Quelques gouttes dans une marinade, un riz sauté ou sur des légumes grillés.", None),
'harissa': ("Pâte de piments rouges, ail et carvi, du Maghreb. Une pointe dans un couscous, une chakchouka ou une mayonnaise.", None),
'curry': ("Mélange d'épices dorées, du plus doux au plus fort. Chauffé dans l'huile avant d'ajouter lait de coco, légumes ou poulet.", None),
'muscade': ("Noix au parfum chaud et boisé, à râper à la minute. Dans une béchamel, une purée ou un gratin dauphinois.", None),
'graines_pavot': ("Petites graines bleu ardoise, croquantes. Sur un pain, un bagel ou dans un gâteau au citron.", None),
'huile_lin': ("Huile dorée aux notes de foin, fragile, à garder au frais. Riche en acides gras oméga-3, toujours utilisée crue.", ('riche', 'omega3')),
'lait_coco': ("Crémeux et parfumé, pilier des cuisines thaïe et antillaise. Dans un curry, un dal ou un riz au lait exotique.", None),
'capres': ("Boutons floraux confits au vinaigre, piquants et salés. Sur un poisson meunière, une tapenade ou une pizza.", None),
'tomate_sechee': ("Séchée au soleil, concentrée et légèrement sucrée. À l'huile avec de l'ail, dans une salade de pâtes ou une focaccia.", None),
'crabe_miettes': ("Chair de crabe prête à l'emploi. En rillettes au citron et à la ciboulette, ou en salade avec un avocat.", None),
'canneberge_sechee': ("Petites baies acidulées d'Amérique du Nord, séchées et sucrées. Dans un granola, une salade d'endives ou une farce de volaille.", None),
'vinaigre_cidre': ("Vinaigre de pomme doux et fruité, de Normandie ou de Bretagne. Dans une vinaigrette au miel, ou pour déglacer une poêlée.", None),
'vinaigre_balsamique': ("Vinaigre de Modène, sombre et doucement sucré. Quelques gouttes sur des fraises, un parmesan ou une salade de tomates.", None),
'spiruline': ("Poudre bleu-vert au goût marin prononcé. Une pincée dans un smoothie banane-mangue ou un pesto, pour sa couleur intense.", None),
'bouillon_pot_au_feu': ("Le bouillon du pot-au-feu, longuement mijoté avec poireau, carotte et clou de girofle. En tasse bien chaud, ou pour cuire des pâtes.", None),
'levure_alimentaire': ("Paillettes dorées au goût de fromage et de noix. À saupoudrer sur des pâtes, une purée, un popcorn ou une salade.", None),
}
