# -*- coding: utf-8 -*-
# Définitions des aliments ajoutés en v2 (les 44 de v1 sont repris tels quels depuis aliments.json).
# F(id, nom, photo_en, categorie, code_ciqual, portion_type, portion_g, cuisines, origine_fr, origine_ue, bio, circuits, prix, saison, **options)
# prix : 'I:<cle>' INSEE (moyenne 12 mois), 'R:<cle>' Familles Rurales juin 2026, 'E:<categorie>' estimation par catégorie.
# saison : 'A:<slug>' ADEME Impact CO2, 'T:<cle>' Interfel/CTIFL, 'ALL' toute l'année (sec, conserve, animal, import), 'NONE' non documentée.
NEW = []
def F(i, nom, en, cat, code, portion, g, cuis, fr, ue, bio, circ, prix, sais, **k):
    NEW.append(dict(id=i, nom=nom, en=en, cat=cat, code=code, portion=portion, g=g, cuis=cuis, fr=fr, ue=ue, bio=bio, circ=circ, prix=prix, sais=sais, **k))

SM, MP, BI, AS, OR, PO, BO, FR_, SU = 'supermarche', 'marche_primeur', 'bio', 'epicerie_asiatique', 'epicerie_orientale', 'poissonnerie', 'boucherie', 'fromagerie', 'surgelés'
FRA, MED, ORI, ASI, LAT, AFR, NOR, UNI = 'francaise', 'mediterraneenne', 'orientale', 'asiatique', 'latino', 'africaine', 'nordique', 'universelle'
BOULEAU = 'pollen de bouleau (Werfel 2015)'
LATEX = 'syndrome latex-fruits (cité par Wagner 2002)'

# ---------------- LÉGUMES ----------------
F('artichaut', 'Artichaut', 'a whole globe artichoke and one halved', 'legume', 20000, '1 artichaut (environ 120 g de partie comestible, cuit)', 120, [FRA, MED], True, True, True, [SM, MP, BI], 'I:artichaut_piece', 'A:artichaut', pc=1)
F('asperge', 'Asperge', 'a small bundle of green asparagus tied with twine', 'legume', 20001, '150 g cuites (6 à 8 asperges)', 150, [FRA, MED, UNI], True, True, True, [SM, MP, BI], 'E:leg2', 'A:asperge')
F('aubergine', 'Aubergine', 'a glossy purple aubergine and one halved', 'legume', 20053, '150 g', 150, [MED, ORI, ASI, FRA], True, True, True, [SM, MP, BI], 'R:aubergine', 'A:aubergine')
F('betterave', 'Betterave rouge cuite', 'two cooked red beetroots, one sliced showing deep crimson rings', 'legume', 20003, '100 g', 100, [FRA, NOR, ORI], True, True, True, [SM, MP, BI], 'E:leg', 'A:betterave', nu=['bétalaïnes (pigment)'], pr=['Colore l’urine et les selles en rouge : sans gravité.'])
F('blette', 'Blette (bette)', 'a bunch of Swiss chard with white stems', 'legume', 20004, '150 g', 150, [FRA, MED, ORI], True, True, True, [MP, BI, SM], 'E:leg', 'A:blette', pr=['Antécédent de calculs rénaux : avis médical (riche en oxalates, comme l’épinard).'])
F('pak_choi', 'Pak-choï (chou chinois)', 'two baby bok choy heads, one halved lengthwise', 'legume', 20167, '150 g', 150, [ASI], True, True, True, [AS, SM, BI], 'E:leg2', 'NONE')
F('celeri_rave', 'Céleri-rave', 'a whole celeriac root and a few thin slices', 'legume', 20055, '100 g', 100, [FRA, NOR], True, True, True, [SM, MP, BI], 'E:leg', 'A:celeri', al=['celeri'], cr=['pollen de bouleau et d’armoise (syndrome céleri-carotte-armoise-épices)'])
F('celeri_branche', 'Céleri branche', 'three crisp celery stalks with leaves', 'legume', 20023, '100 g', 100, [FRA, UNI], True, True, True, [SM, MP, BI], 'E:leg', 'T:celeri_branche', al=['celeri'], cr=['pollen de bouleau et d’armoise (syndrome céleri-carotte-armoise-épices)'])
F('champignon_paris', 'Champignon de Paris', 'a handful of white button mushrooms, one sliced', 'legume', 20010, '100 g', 100, [FRA, UNI], True, True, True, [SM, MP, BI], 'I:champignon', 'T:champignon_paris', pr=['Toujours bien cuits pour les personnes immunodéprimées (règle générale d’hygiène).'], sg='Conserve possible (moins savoureuse) ; frais de préférence.')
F('shiitake', 'Shiitaké', 'a few fresh shiitake mushrooms on dark ceramic', 'legume', 20212, '80 g cuits', 80, [ASI], True, True, True, [AS, BI, SM], 'E:leg2', 'NONE', pr=['Toujours bien cuit : le shiitaké cru ou peu cuit peut provoquer une dermatite « flagellée » (réaction cutanée connue).'])
F('chou_blanc', 'Chou blanc', 'a crisp white cabbage cut in half', 'legume', 20116, '100 g', 100, [FRA, NOR, UNI], True, True, True, [SM, MP, BI], 'E:leg', 'A:chou')
F('chou_rouge', 'Chou rouge', 'a red cabbage cut in half showing purple layers', 'legume', 20014, '100 g', 100, [FRA, NOR, UNI], True, True, True, [SM, MP, BI], 'E:leg', 'A:chou', nu=['anthocyanes (pigment)'])
F('chou_vert', 'Chou vert (pommé frisé)', 'a savoy cabbage with crinkled leaves', 'legume', 20069, '150 g', 150, [FRA, NOR], True, True, True, [SM, MP, BI], 'E:leg', 'A:chou')
F('chou_fleur', 'Chou-fleur', 'a whole cauliflower head and a few florets', 'legume', 20016, '150 g', 150, [FRA, ORI, ASI, UNI], True, True, True, [SM, MP, BI], 'I:choufleur_piece', 'A:choufleur', fz=20082)
F('chou_bruxelles', 'Chou de Bruxelles', 'a small pile of Brussels sprouts, some halved', 'legume', 20058, '150 g', 150, [FRA, NOR], True, True, True, [SM, MP, BI], 'E:leg', 'A:choudebruxelles', fz=20206)
F('romanesco', 'Chou romanesco', 'a romanesco cauliflower with fractal spirals', 'legume', 20280, '150 g', 150, [FRA, MED], True, True, True, [MP, BI, SM], 'E:leg', 'NONE')
F('concombre', 'Concombre', 'a whole cucumber and thin slices', 'legume', 20019, '150 g', 150, [MED, ORI, ASI, NOR, UNI], True, True, True, [SM, MP, BI], 'R:concombre', 'A:concombre')
F('courgette', 'Courgette', 'two green courgettes, one sliced into rounds', 'legume', 20020, '200 g', 200, [FRA, MED, ORI, UNI], True, True, True, [SM, MP, BI], 'I:courgette', 'A:courgette', fz=20230)
F('cresson', 'Cresson de fontaine', 'a bunch of fresh watercress', 'legume', 20022, '60 g', 60, [FRA, NOR], True, True, True, [MP, SM, BI], 'E:leg2', 'A:cresson', pr=['Cresson sauvage : jamais cru (risque de douve du foie) ; le cresson de fontaine cultivé du commerce se consomme cru.'])
F('endive', 'Endive', 'three Belgian endives, one halved', 'legume', 20026, '150 g', 150, [FRA, NOR], True, True, True, [SM, MP, BI], 'I:endive', 'A:endive')
F('fenouil', 'Fenouil', 'a fennel bulb with fronds, one halved', 'legume', 20028, '150 g', 150, [MED, FRA], True, True, True, [SM, MP, BI], 'E:leg', 'A:fenouil')
F('haricot_vert', 'Haricot vert', 'a handful of thin green beans', 'legume', 20061, '150 g', 150, [FRA, AFR, ASI, UNI], True, True, True, [SM, MP, BI, SU], 'I:haricotvert', 'A:haricotvert', fz=20070)
F('laitue', 'Laitue', 'a fresh green butterhead lettuce', 'legume', 20031, '80 g', 80, [FRA, UNI], True, True, True, [SM, MP, BI], 'R:laitue', 'A:laitue')
F('roquette', 'Roquette', 'a small heap of wild rocket leaves', 'legume', 20217, '50 g', 50, [MED, FRA], True, True, True, [SM, MP, BI], 'E:leg2', 'T:salade')
F('navet', 'Navet', 'three small purple-top turnips', 'legume', 20064, '150 g', 150, [FRA, NOR, ASI], True, True, True, [SM, MP, BI], 'E:leg', 'A:navet')
F('oignon', 'Oignon', 'a yellow onion and a halved red onion', 'legume', 20034, '50 g', 50, [UNI], True, True, True, [SM, MP, BI], 'I:oignon', 'A:oignon', cp=[])
F('echalote', 'Échalote', 'a few shallots in their copper skins', 'legume', 20097, '20 g', 20, [FRA, ASI], True, True, True, [SM, MP, BI], 'E:epice', 'A:echalote', cp=[], noclaim=True)
F('poireau', 'Poireau', 'two leeks with dark green tops', 'legume', 20039, '150 g', 150, [FRA, NOR], True, True, True, [SM, MP, BI], 'I:poireau', 'A:poireau', fz=20236)
F('petits_pois', 'Petits pois', 'fresh green peas spilling from open pods', 'legume', 20072, '150 g', 150, [FRA, ASI, UNI], True, True, True, [SM, MP, BI, SU], 'E:leg', 'A:petitpois', fz=20084)
F('feve', 'Fève', 'shelled broad beans in a small ceramic bowl', 'legumineuse', 20500, '150 g cuites', 150, [MED, ORI, FRA], True, True, True, [SM, MP, OR, SU], 'E:sec', 'ALL', sais_note='vendue sèche, surgelée ou en conserve toute l’année ; fraîche au printemps (aucun calendrier officiel consulté ne couvre la fève)', pr=['Déficit en G6PD (favisme) : ne jamais consommer de fèves (risque d’hémolyse grave).'])
F('potiron', 'Potiron', 'a wedge of orange pumpkin with seeds', 'legume', 20044, '200 g', 200, [FRA, AFR, LAT, UNI], True, True, True, [SM, MP, BI], 'E:leg', 'A:potiron')
F('potimarron', 'Potimarron', 'a whole red kuri squash and a wedge', 'legume', 20132, '200 g', 200, [FRA, ASI], True, True, True, [SM, MP, BI], 'E:leg', 'A:courge')
F('radis', 'Radis rose', 'a bunch of pink radishes with leaves', 'legume', 20045, '80 g', 80, [FRA, ASI], True, True, True, [SM, MP, BI], 'E:leg', 'A:radis')
F('radis_noir', 'Radis noir', 'a black radish, one sliced showing white flesh', 'legume', 20089, '80 g', 80, [FRA, ASI], True, True, True, [MP, BI], 'E:leg', 'NONE')
F('panais', 'Panais', 'three creamy parsnips', 'legume', 20181, '150 g', 150, [FRA, NOR], True, True, True, [MP, BI, SM], 'E:leg', 'A:panais')
F('topinambour', 'Topinambour', 'a handful of knobbly Jerusalem artichokes', 'legume', 20196, '150 g', 150, [FRA], True, True, True, [MP, BI], 'E:leg', 'A:topinambour', pr=['Riche en inuline : ballonnements possibles, introduire progressivement.'])
F('salsifis', 'Salsifis', 'peeled salsify roots on a linen cloth', 'legume', 20046, '150 g cuits', 150, [FRA], True, True, True, [MP, SM, SU], 'E:leg', 'A:salsifis')
F('gombo', 'Gombo', 'a handful of fresh okra pods', 'legume', 58103, '150 g cuits', 150, [AFR, ORI, ASI, LAT], False, True, False, [OR, AS, MP], 'E:leg2', 'NONE')
F('mais_doux', 'Maïs doux', 'sweet corn kernels in a small bowl and a cob', 'legume', 20066, '100 g', 100, [LAT, AFR, UNI], True, True, True, [SM, SU], 'E:leg', 'A:mais', cp=[])
F('poivron_jaune', 'Poivron jaune', 'a glossy yellow bell pepper and one halved', 'legume', 20168, '100 g (un demi-poivron)', 100, [MED, LAT, ASI, UNI], True, True, True, [SM, MP, BI], 'I:poivron', 'A:poivron', cr=[LATEX])
F('tomate_cerise', 'Tomate cerise', 'a vine of red cherry tomatoes', 'legume', 20172, '100 g', 100, [MED, UNI], True, True, True, [SM, MP, BI], 'E:leg2', 'A:tomate', cr=['syndrome latex-fruits (tomate citée par Wagner 2002)'], nu=['lycopène'])
F('pomme_de_terre', 'Pomme de terre', 'three potatoes with a light dusting of soil', 'feculent', 4003, '200 g cuites', 200, [FRA, NOR, LAT, UNI], True, True, True, [SM, MP, BI], 'I:pdt', 'ALL', cp=[], cr=['syndrome latex-fruits (pomme de terre citée par Wagner 2002)'], sais_note='conservation : disponible toute l’année (hors calendrier Interfel)')
F('manioc', 'Manioc (racine cuite)', 'a peeled cassava root and cooked chunks', 'feculent', 54034, '150 g cuit', 150, [AFR, LAT], False, False, False, [OR, AS], 'E:exo', 'ALL', cp=[], pr=['Jamais cru : la racine crue contient des glucosides cyanogènes ; toujours épluchée et bien cuite.'])
F('igname', 'Igname', 'a yam tuber and peeled cooked slices', 'feculent', 53503, '150 g cuite', 150, [AFR, LAT], False, False, False, [OR, AS], 'E:exo', 'ALL', cp=[], pr=['Toujours cuite.'])
F('banane_plantain', 'Banane plantain', 'two plantains, one peeled and sliced', 'feculent', 53101, '150 g cuite', 150, [AFR, LAT], False, False, False, [OR, AS, SM], 'E:exo', 'ALL', cp=[], cr=['syndrome latex-fruits (banane citée par Wagner 2002)'])
F('nori', 'Algue nori', 'a few dark green nori sheets stacked', 'algue', 20987, '2 g (une feuille)', 2, [ASI], True, True, True, [AS, BI, SM], 'E:algue', 'ALL', cp=[], noclaim=True, et=['ANSES_ALGUES'], gl='C',
  pr=['Algues : déconseillées en cas de maladie de la thyroïde, maladie cardiaque, insuffisance rénale, traitement à l’amiodarone ou au lithium, grossesse et allaitement sans avis médical (ANSES 2018).', 'Teneur en iode très variable selon les lots : jamais en grande quantité ni tous les jours.'],
  me="Utilisée en très petite quantité (une feuille) ; teneur en iode très variable, d'où les restrictions de l'ANSES.")
F('wakame', 'Algue wakamé', 'rehydrated wakame seaweed in a small black bowl', 'algue', 20984, '2 g séchée (une cuillère à café)', 2, [ASI], True, True, True, [AS, BI], 'E:algue', 'ALL', cp=[], noclaim=True, et=['ANSES_ALGUES'], gl='C',
  pr=['Algues : déconseillées en cas de maladie de la thyroïde, maladie cardiaque, insuffisance rénale, traitement à l’amiodarone ou au lithium, grossesse et allaitement sans avis médical (ANSES 2018).', 'Teneur en iode très variable selon les lots : jamais en grande quantité ni tous les jours.'],
  me="Utilisée en très petite quantité ; l'iode des algues peut dépasser les apports sûrs, d'où les restrictions de l'ANSES.")

# ---------------- FRUITS ----------------
F('pomme', 'Pomme', 'a crisp red apple and one halved', 'fruit', 13039, '150 g (1 pomme)', 150, [FRA, NOR, UNI], True, True, True, [SM, MP, BI], 'I:pomme', 'A:pomme', cr=[BOULEAU])
F('poire', 'Poire', 'a ripe pear and one halved', 'fruit', 13037, '150 g (1 poire)', 150, [FRA, UNI], True, True, True, [SM, MP, BI], 'I:poire', 'A:poire', cr=[BOULEAU])
F('cerise', 'Cerise', 'a handful of dark red cherries with stems', 'fruit', 13008, '150 g', 150, [FRA, MED], True, True, True, [SM, MP, BI], 'R:cerise', 'A:cerise', cr=[BOULEAU])
F('prune', 'Prune', 'a few purple plums, one halved', 'fruit', 13100, '150 g', 150, [FRA, NOR], True, True, True, [SM, MP, BI], 'E:fruit', 'A:prune', cr=[BOULEAU])
F('mirabelle_reine_claude', 'Reine-claude', 'green gage plums on a linen cloth', 'fruit', 13041, '150 g', 150, [FRA], True, True, True, [MP, SM], 'E:fruit', 'A:reineclaude', cr=[BOULEAU])
F('peche', 'Pêche', 'a ripe yellow peach and one halved', 'fruit', 13043, '150 g (1 pêche)', 150, [FRA, MED], True, True, True, [SM, MP, BI], 'R:peche', 'A:peche', cr=[BOULEAU, 'syndrome latex-fruits (pêche citée par Wagner 2002)', 'allergie à la LTP de la pêche (fréquente en zone méditerranéenne)'])
F('nectarine', 'Nectarine', 'two nectarines, one halved', 'fruit', 13030, '150 g', 150, [FRA, MED], True, True, True, [SM, MP, BI], 'R:peche', 'A:nectarine', cr=[BOULEAU, 'allergie à la LTP de la pêche (famille proche)'])
F('raisin', 'Raisin', 'a bunch of black grapes', 'fruit', 13112, '150 g', 150, [FRA, MED, UNI], True, True, True, [SM, MP, BI], 'E:fruit', 'A:raisin')
F('figue', 'Figue fraîche', 'three fresh purple figs, one opened', 'fruit', 13012, '100 g (2 figues)', 100, [MED, ORI, FRA], True, True, True, [SM, MP, BI], 'E:fruit2', 'A:figue')
F('melon', 'Melon charentais', 'half a cantaloupe melon with orange flesh', 'fruit', 13026, '200 g', 200, [FRA, MED], True, True, True, [SM, MP, BI], 'R:melon', 'A:melon')
F('pasteque', 'Pastèque', 'a triangular slice of watermelon', 'fruit', 13036, '250 g', 250, [MED, AFR, UNI], True, True, True, [SM, MP], 'R:pasteque', 'A:pasteque', nu=['lycopène'])
F('framboise', 'Framboise', 'a small bowl of fresh raspberries', 'fruit', 13015, '125 g (1 barquette)', 125, [FRA, NOR, UNI], True, True, True, [SM, MP, BI, SU], 'E:fruit2', 'T:petits_fruits_rouges', fz=13136)
F('groseille', 'Groseille', 'strings of glossy redcurrants', 'fruit', 13019, '100 g', 100, [FRA, NOR], True, True, True, [MP, SM, BI], 'E:fruit2', 'A:groseille')
F('mure', 'Mûre', 'a small heap of blackberries', 'fruit', 13029, '125 g', 125, [FRA, NOR], True, True, True, [MP, SU, BI], 'E:fruit2', 'A:mure', fz=13150)
F('rhubarbe', 'Rhubarbe', 'three pink rhubarb stalks', 'fruit', 13047, '150 g (cuite, peu sucrée)', 150, [FRA, NOR], True, True, True, [MP, BI], 'E:fruit', 'A:rhubarbe', pr=['Ne consommer que les tiges (feuilles toxiques).', 'Antécédent de calculs rénaux : avis médical (riche en oxalates).'])
F('coing', 'Coing', 'a golden quince with fuzzy skin', 'fruit', 13010, '150 g (cuit)', 150, [FRA, ORI, MED], True, True, True, [MP, BI], 'E:fruit', 'A:coing')
F('citron', 'Citron', 'a lemon and one halved', 'fruit', 13009, '30 g de jus ou de pulpe', 30, [UNI], True, True, True, [SM, MP, BI], 'I:citron', 'A:citron', cp=[])
F('citron_vert', 'Citron vert', 'two limes, one halved', 'fruit', 13067, '30 g de jus ou de pulpe', 30, [LAT, ASI, AFR], False, False, True, [SM, AS, BI], 'E:exo', 'ALL', cp=[])
F('clementine', 'Clémentine', 'three clementines, one peeled', 'fruit', 13024, '150 g (2 clémentines)', 150, [FRA, MED, UNI], True, True, True, [SM, MP, BI], 'I:clementine', 'A:clementine')
F('banane', 'Banane', 'a ripe banana and a few slices', 'fruit', 13005, '120 g (1 banane)', 120, [UNI, AFR, LAT], False, True, True, [SM, MP, BI], 'I:banane', 'A:banane', cr=['syndrome latex-fruits (banane citée par Wagner 2002)'])
F('mangue', 'Mangue', 'a ripe mango cut into a hedgehog pattern', 'fruit', 13025, '85 g (un tiers de mangue)', 85, [LAT, ASI, AFR], False, True, True, [SM, AS, OR], 'E:exo', 'A:manguebateau',
  gp='C', et=['FAM20', 'AUNE17'], me="Fruit riche en bêta-carotène ; un petit essai pilote (85 g/j, sans groupe sans mangue) a vu moins de rides profondes, mais 250 g/j ont donné l'effet inverse. Financement partiel National Mango Board.",
  pr=['Allergie possible aux personnes sensibles à la noix de cajou ou à la pistache (même famille botanique), peau du fruit irritante chez certains.'])
F('papaye', 'Papaye', 'half a papaya with black seeds', 'fruit', 13035, '150 g', 150, [LAT, ASI, AFR], False, False, False, [SM, AS, OR], 'E:exo', 'ALL', cr=['syndrome latex-fruits (papaïne, réactions décrites chez des allergiques au latex)'])
F('ananas', 'Ananas', 'a pineapple and a few wedges', 'fruit', 13002, '150 g', 150, [LAT, ASI, AFR], False, False, True, [SM, AS], 'E:exo', 'A:ananas')
F('goyave', 'Goyave', 'two guavas, one halved showing pink flesh', 'fruit', 13083, '100 g', 100, [LAT, ASI, AFR], False, False, False, [AS, OR], 'E:exo', 'ALL', nu=['lycopène (goyave rose)'])
F('fruit_passion', 'Fruit de la passion', 'two passion fruits, one halved', 'fruit', 13016, '50 g (2 fruits)', 50, [LAT, AFR, ASI], False, False, False, [SM, AS], 'E:exo', 'A:fruitdelapassion')
F('litchi', 'Litchi', 'a few lychees, one peeled', 'fruit', 13023, '100 g', 100, [ASI], False, False, False, [SM, AS], 'E:exo', 'T:litchi')
F('kaki', 'Kaki', 'two ripe persimmons, one halved', 'fruit', 13066, '150 g', 150, [ASI, MED], False, True, False, [SM, MP, AS], 'E:exo', 'A:kaki')
F('grenade', 'Grenade', 'a pomegranate broken open showing red seeds', 'fruit', 13018, '100 g de grains', 100, [ORI, MED, ASI], False, True, True, [SM, MP, OR], 'E:exo', 'A:grenade', cp=['rougeurs'], gp='C',
  et=['HENNING19', 'AUNE17'], me="Fruit riche en polyphénols ; un essai (74 femmes) a vu une meilleure résistance au coup de soleil avec 240 mL de jus ou un extrait par jour pendant 12 semaines, en ouvert : pas testé pour le fruit entier.",
  pr=['L’essai porte sur le jus ou un extrait (fournis par POM Wonderful), pas sur les grains.'])
F('figue_barbarie', 'Figue de Barbarie', 'prickly pears, one peeled showing magenta flesh', 'fruit', 13063, '150 g', 150, [ORI, MED, LAT], False, True, False, [OR, MP], 'E:exo', 'NONE', pr=['Nombreux pépins durs : consommer avec modération en cas de troubles digestifs.'])
F('kumquat', 'Kumquat', 'a handful of kumquats with leaves', 'fruit', 13549, '50 g', 50, [ASI], False, True, False, [AS, SM], 'E:exo', 'NONE')
F('olive', 'Olive', 'a small bowl of green and black olives', 'fruit', 13033, '30 g (une dizaine)', 30, [MED, ORI], True, True, True, [SM, MP, OR, BI], 'E:noix', 'ALL', cp=[], sais_note='conserve en saumure : toute l’année')
F('chataigne', 'Châtaigne', 'roasted chestnuts in a paper cone', 'feculent', 15020, '100 g cuites', 100, [FRA, ASI], True, True, True, [SM, MP, BI], 'E:noix', 'A:chataigne', cp=[], cr=['syndrome latex-fruits (châtaigne citée par Wagner 2002)'], pr=['La châtaigne n’est pas un « fruit à coque » au sens des 14 allergènes réglementés, mais des allergies existent.'])

# ---------------- FRUITS SECS ----------------
F('datte', 'Datte', 'a few glossy medjool dates on a small plate', 'fruit_sec', 13011, '30 g (3 dattes)', 30, [ORI, AFR], False, False, True, [SM, OR, BI], 'E:exo', 'A:datte', cp=[], pr=['Sucres naturellement concentrés : petite portion ; diabète : avis médical.'], gl='C', cl=[])
F('figue_seche', 'Figue sèche', 'a few dried figs', 'fruit_sec', 13013, '30 g (2 figues)', 30, [ORI, MED], False, True, True, [SM, OR, BI], 'E:noix', 'ALL', cp=[], pr=['Sucres naturellement concentrés : petite portion.', 'Sulfites possibles selon les marques : lire l’étiquette en cas d’allergie aux sulfites.'], gl='C', cl=[])
F('pruneau', 'Pruneau', 'a few prunes in a small ceramic dish', 'fruit_sec', 13042, '30 g (3 à 4 pruneaux)', 30, [FRA], True, True, True, [SM, BI], 'E:noix', 'ALL', cp=[], pr=['Sucres naturellement concentrés et effet laxatif : petite portion.'], gl='C', cl=[])
F('raisin_sec', 'Raisin sec', 'a small heap of dark raisins', 'fruit_sec', 13046, '20 g', 20, [ORI, MED, UNI], False, True, True, [SM, OR, BI], 'E:noix', 'ALL', cp=[], pr=['Sucres naturellement concentrés : petite portion.', 'Sulfites possibles (raisins blonds surtout) : lire l’étiquette en cas d’allergie aux sulfites.'], gl='C', cl=[])
F('abricot_sec', 'Abricot sec', 'a few dried apricots', 'fruit_sec', 13001, '30 g (4 abricots)', 30, [ORI, MED], False, True, True, [SM, OR, BI], 'E:noix', 'ALL', cp=['eclat'], al=['sulfites'], pr=['Souvent traités aux sulfites (abricots orangés) : allergène à déclarer ; les abricots secs bruns non soufrés n’en contiennent pas.', 'Sucres naturellement concentrés : petite portion.'], gl='C', cl=[])

# ---------------- LÉGUMINEUSES ----------------
F('lentille_verte_puy', 'Lentille verte du Puy', 'green Puy lentils in a small ceramic bowl', 'legumineuse', 20587, '150 g cuites (60 g sèches)', 150, [FRA], True, True, True, [SM, BI], 'E:sec', 'ALL', nu=['AOP française (Haute-Loire)'])
F('lentille_corail', 'Lentille corail', 'coral red lentils in a small bowl', 'legumineuse', 20589, '150 g cuites (60 g sèches)', 150, [ORI, ASI, UNI], False, True, True, [SM, BI, OR, AS], 'E:sec', 'ALL')
F('pois_casse', 'Pois cassé', 'split green peas in a ceramic bowl', 'legumineuse', 20506, '150 g cuits', 150, [FRA, NOR], True, True, True, [SM, BI], 'E:sec', 'ALL')
F('haricot_blanc', 'Haricot blanc (lingot)', 'cooked white beans in a small bowl', 'legumineuse', 20502, '150 g cuits', 150, [FRA, MED, UNI], True, True, True, [SM, BI], 'E:sec', 'ALL', nu=['IGP Lingot du Nord possible'])
F('flageolet', 'Flageolet', 'pale green flageolet beans in a bowl', 'legumineuse', 20540, '150 g cuits', 150, [FRA], True, True, True, [SM, BI], 'E:sec', 'ALL')
F('haricot_mungo', 'Haricot mungo', 'small green mung beans in a bowl', 'legumineuse', 20531, '150 g cuits', 150, [ASI], False, False, True, [AS, BI], 'E:sec', 'ALL', pr=['Germes de haricot mungo : toujours cuits (graines germées crues déconseillées aux femmes enceintes et aux personnes fragiles).'])
F('houmous', 'Houmous', 'a swirl of hummus with olive oil and paprika', 'legumineuse', 25621, '50 g', 50, [ORI, MED], False, True, True, [SM, OR, BI], 'E:sec', 'ALL', al=['sesame'], pr=['Contient de la purée de sésame (allergène) ; préemballé souvent salé.'], sg='Frais uniquement ; maison possible avec des pois chiches en conserve.')

# ---------------- SOJA ----------------
SOJA_PR = ['Allergène majeur (soja).', 'Grossesse et allaitement : recommandation française de ne pas consommer de soja (Santé.fr).', 'Enfants de moins de 3 ans : déconseillé (Afssa 2005).', 'Antécédent personnel ou familial de cancer du sein : avis médical (Afssa 2005).']
F('tempeh', 'Tempeh', 'a block of tempeh, one side sliced', 'soja', 20917, '100 g', 100, [ASI], False, True, True, [BI, AS], 'E:soja', 'ALL', al=['soja'], cr=['pollen de bouleau (protéine Gly m 4 du soja, Werfel 2015)'], pr=SOJA_PR + ['Toujours cuit.'], et=['IZUMI07', 'WASTYK21'], gl='C')
F('miso', 'Miso', 'a spoon of miso paste on a small dish', 'soja', 20916, '15 g (1 cuillère à soupe)', 15, [ASI], False, True, True, [AS, BI], 'E:soja', 'ALL', al=['soja', 'cereales_gluten'], cp=[], noclaim=True, cr=['pollen de bouleau (protéine Gly m 4 du soja, Werfel 2015)'],
  pr=SOJA_PR + ['Très salé : petite quantité ; hypertension ou maladie rénale : avis médical.', 'Souvent fabriqué avec de l’orge ou du blé (gluten) : lire l’étiquette.'], gl='C', et=['WASTYK21'])
F('tofu_soyeux', 'Tofu soyeux', 'silken tofu block on a black plate', 'soja', 20906, '100 g', 100, [ASI], False, True, True, [BI, AS, SM], 'E:soja', 'ALL', al=['soja'], cr=['pollen de bouleau (protéine Gly m 4 du soja, Werfel 2015)'], pr=SOJA_PR, et=['IZUMI07'], gl='C')
F('boisson_soja_calcium', 'Boisson au soja enrichie en calcium', 'a glass of plant milk next to soybeans', 'soja', 18901, '200 mL', 200, [UNI, ASI], True, True, True, [SM, BI], 'E:laitier', 'ALL', al=['soja'], cp=[], cr=['pollen de bouleau (protéine Gly m 4 du soja, Werfel 2015)'], pr=SOJA_PR, gl='C', cl=[], et=['IZUMI07'])

# ---------------- CÉRÉALES ET FÉCULENTS ----------------
F('riz_complet', 'Riz complet', 'cooked brown rice in a ceramic bowl', 'cereale_complete', 9103, '150 g cuit (50 g cru)', 150, [ASI, LAT, AFR, UNI], True, True, True, [SM, BI, AS], 'E:sec', 'ALL', pr=['Le riz contient de l’arsenic inorganique (plus dans le complet) : varier les céréales, rincer et cuire dans beaucoup d’eau.'])
F('riz_basmati', 'Riz basmati', 'cooked basmati rice in a bowl', 'feculent', 9125, '150 g cuit (50 g cru)', 150, [ASI, ORI, AFR, UNI], False, True, True, [SM, BI, AS, OR], 'E:sec', 'ALL', cp=[], gl='C', cl=[], pr=['Céréale raffinée : charge glycémique plus élevée que le riz complet ; à associer à des légumes et légumineuses.'])
F('sarrasin', 'Sarrasin (graines)', 'toasted buckwheat groats in a bowl', 'cereale_complete', 9380, '50 g cru', 50, [FRA, NOR, ASI], True, True, True, [SM, BI], 'E:sec', 'ALL', gl='B', pr=['Naturellement sans gluten, mais contamination croisée possible : chercher la mention « sans gluten » en cas de maladie cœliaque.', 'Allergie au sarrasin possible (rare, parfois sévère).'])
F('galette_sarrasin', 'Galette de sarrasin', 'a folded buckwheat crêpe on a plate', 'cereale_complete', 23801, '1 galette (60 g)', 60, [FRA], True, True, True, [SM, BI], 'E:sec', 'ALL', gl='B', pr=['Certaines galettes du commerce contiennent aussi de la farine de blé : lire l’étiquette (gluten).'])
F('quinoa', 'Quinoa', 'cooked quinoa in a small bowl', 'cereale_complete', 9341, '150 g cuit (50 g cru)', 150, [LAT, UNI], True, True, True, [SM, BI], 'E:sec', 'ALL', gl='B', pr=['Rincer avant cuisson (saponines amères).'])
F('boulgour', 'Boulgour', 'cooked bulgur wheat in a bowl', 'cereale_complete', 9691, '150 g cuit (50 g cru)', 150, [ORI, MED], False, True, True, [SM, OR, BI], 'E:sec', 'ALL', al=['cereales_gluten'])
F('orge_perlee', 'Orge perlée', 'pearl barley in a ceramic bowl', 'cereale_complete', 9322, '150 g cuite', 150, [NOR, FRA, ORI], True, True, True, [SM, BI], 'E:sec', 'ALL', al=['cereales_gluten'], pr=['L’orge perlée est en partie décortiquée : un peu moins de fibres que l’orge entière.'])
F('epeautre', 'Épeautre (grains)', 'spelt grains in a bowl', 'cereale_complete', 9001, '50 g cru', 50, [FRA], True, True, True, [BI, SM], 'E:sec', 'ALL', al=['cereales_gluten'])
F('millet', 'Millet', 'cooked millet in a bowl', 'cereale_complete', 9331, '150 g cuit', 150, [AFR, ASI], False, True, True, [BI, OR, AS], 'E:sec', 'ALL', gl='B')
F('pates_completes', 'Pâtes complètes', 'cooked wholewheat penne in a bowl', 'cereale_complete', 9871, '150 g cuites (60 g crues)', 150, [MED, UNI], True, True, True, [SM, BI], 'E:sec', 'ALL', al=['cereales_gluten'])
F('pain_seigle', 'Pain de seigle', 'two slices of dark rye bread', 'cereale_complete', 7125, '50 g (2 tranches)', 50, [NOR, FRA], True, True, True, [SM, BI], 'E:sec', 'ALL', al=['cereales_gluten'], pr=['Pain de seigle et froment : contient du blé.'])
F('couscous', 'Semoule de couscous', 'fluffy couscous grains in a bowl', 'feculent', 9683, '150 g cuite (50 g crue)', 150, [ORI, AFR], False, True, True, [SM, OR], 'E:sec', 'ALL', al=['cereales_gluten'], cp=[], gl='C', cl=[], pr=['Semoule raffinée ; une version complète existe (plus de fibres).'])
F('polenta', 'Polenta', 'a mound of soft polenta', 'feculent', 9615, '150 g cuite', 150, [MED, LAT], False, True, True, [SM, BI], 'E:sec', 'ALL', cp=[], gl='C', cl=[])
F('tortilla_mais', 'Tortilla de maïs', 'a small stack of corn tortillas', 'feculent', 7813, '2 tortillas (60 g)', 60, [LAT], False, False, True, [SM], 'E:sec', 'ALL', cp=[], gl='C', cl=[], pr=['Certaines tortillas « maïs » contiennent aussi du blé : lire l’étiquette.'])
F('vermicelle_riz', 'Vermicelle de riz', 'rice vermicelli nests', 'feculent', 9901, '150 g cuite (50 g sèche)', 150, [ASI], False, False, False, [AS, SM], 'E:sec', 'ALL', cp=[], gl='C', cl=[])
F('son_avoine', 'Son d’avoine', 'oat bran in a small wooden spoon', 'cereale_complete', 9640, '20 g (2 cuillères à soupe)', 20, [UNI, NOR], True, True, True, [SM, BI], 'E:sec', 'ALL', al=['cereales_gluten'], nu=['bêta-glucanes'])

# ---------------- FRUITS À COQUE ET GRAINES ----------------
FAC = ['Allergène majeur (fruits à coque).']
F('pistache', 'Pistache', 'a handful of shelled pistachios', 'fruit_a_coque', 15044, '30 g', 30, [ORI, MED], False, True, True, [SM, OR, BI], 'E:noix', 'ALL', al=['fruits_a_coque'], cr=['noix de cajou et mangue (même famille, co-sensibilisation fréquente)'], gl='B', pr=['Préférer non salées.'])
F('noix_cajou', 'Noix de cajou', 'a handful of cashew nuts', 'fruit_a_coque', 15054, '30 g', 30, [ASI, AFR, LAT], False, False, True, [SM, BI, AS], 'E:noix', 'ALL', al=['fruits_a_coque'], cr=['pistache (co-sensibilisation fréquente)'], gl='B', pr=['Préférer non salées.'])
F('noix_pecan', 'Noix de pécan', 'a handful of pecan halves', 'fruit_a_coque', 15026, '30 g', 30, [LAT, UNI], False, False, True, [SM, BI], 'E:noix', 'ALL', al=['fruits_a_coque'], cr=['noix (co-sensibilisation fréquente)'], gl='B')
F('macadamia', 'Noix de macadamia', 'a few macadamia nuts', 'fruit_a_coque', 15027, '30 g', 30, [UNI], False, False, True, [SM, BI], 'E:noix', 'ALL', al=['fruits_a_coque'], gl='B')
F('cacahuete', 'Cacahuète (arachide)', 'a handful of unsalted roasted peanuts', 'legumineuse', 15053, '30 g', 30, [AFR, ASI, LAT], True, True, True, [SM, BI, OR, AS], 'E:noix', 'ALL', al=['arachides'], cp=['texture'], gl='B', et=['BAO13', 'AUNE16N'],
  cr=['autres légumineuses (lupin, soja) chez certains ; avis allergologue'], pr=['Allergène majeur (arachide), réactions parfois graves.', 'Préférer non salées.'], me="Légumineuse riche en lipides ; les fruits à coque et l'arachide sont associés à une mortalité plus faible dans les cohortes ; aucun essai cutané.")
F('beurre_cacahuete', 'Beurre de cacahuète', 'a spoon of smooth peanut butter', 'legumineuse', 15202, '20 g (1 cuillère à soupe)', 20, [AFR, LAT, UNI], False, True, True, [SM, BI], 'E:noix', 'ALL', al=['arachides'], cp=[], gl='C', cl=[], pr=['Allergène majeur (arachide).', 'Choisir 100 % arachide, sans sucre ni huile de palme ajoutés.'])
F('pignon', 'Pignon de pin', 'a small heap of pine nuts', 'graine', 15025, '15 g', 15, [MED, ORI], False, True, True, [SM, BI, OR], 'E:noix', 'ALL', pr=['Le pignon n’est pas dans la liste des fruits à coque réglementés, mais des allergies existent.', 'Rare « syndrome du pignon » : goût amer durable, sans gravité.'])
F('sesame', 'Graines de sésame', 'white and black sesame seeds in two small dishes', 'graine', 15010, '10 g (1 cuillère à soupe)', 10, [ASI, ORI], False, True, True, [SM, BI, AS, OR], 'E:noix', 'ALL', al=['sesame'], pr=['Allergène majeur (sésame).'])
F('tahin', 'Tahin (purée de sésame)', 'a small jar of tahini with a spoon', 'graine', 15203, '15 g (1 cuillère à soupe)', 15, [ORI, MED], False, True, True, [SM, OR, BI], 'E:noix', 'ALL', al=['sesame'], pr=['Allergène majeur (sésame).'])
F('noix_coco_rapee', 'Noix de coco râpée', 'a small bowl of desiccated coconut', 'fruit_sec', 15007, '10 g', 10, [ASI, AFR, LAT], False, False, True, [SM, AS, BI], 'E:noix', 'ALL', cp=[], gl='C', cl=[], pr=['Riche en graisses saturées : petite quantité.', 'La noix de coco n’est pas un fruit à coque réglementé ; allergie rare.'])

# ---------------- MATIÈRES GRASSES ----------------
F('huile_colza', 'Huile de colza', 'a small glass cruet of golden rapeseed oil', 'matiere_grasse', 17130, '10 g (1 cuillère à soupe)', 10, [FRA, NOR, UNI], True, True, True, [SM, BI], 'E:huile', 'ALL', cp=['rides_fermete'], gl='C', cl=['acides_gras_omega3'], et=['LATREILLE13', 'PAN12'], nu=['ALA (oméga-3 végétal)', 'vitamine E'],
  me="Huile la plus riche en ALA parmi les huiles courantes de cuisson douce ; l'ALA alimentaire est associé à moins de photovieillissement dans une cohorte française (observationnel).", pr=['Pour l’assaisonnement ou la cuisson douce, pas pour la friture.'])
F('huile_noix', 'Huile de noix', 'a small bottle of walnut oil and two walnuts', 'matiere_grasse', 17220, '10 g (1 cuillère à soupe)', 10, [FRA], True, True, True, [SM, BI], 'E:huile', 'ALL', cp=['rides_fermete'], gl='C', cl=['acides_gras_omega3'], et=['LATREILLE13', 'PAN12'], nu=['ALA (oméga-3 végétal)'],
  me="Huile riche en ALA, à utiliser crue ; l'ALA alimentaire est associé à moins de photovieillissement dans une cohorte française (observationnel).", pr=['Crue uniquement (fragile à la chaleur) ; se conserve au frais après ouverture.', 'Allergie aux noix : l’huile vierge peut contenir des protéines de noix, avis allergologue.'])

# ---------------- POISSONS ----------------
PO_PR = ['Allergène majeur (poissons).', 'Grossesse : poisson 2 fois par semaine dont un gras, bien cuit ; éviter cru ou fumé (Santé.fr).']
F('hareng', 'Hareng', 'a grilled herring fillet on a plate', 'poisson', 26014, '100 g', 100, [NOR, FRA], True, True, False, [PO, SM], 'E:poisgras', 'ALL', al=['poissons'], cr=['autres poissons (parvalbumine, avis allergologue)'], pr=PO_PR + ['Hareng fumé ou mariné : très salé, et à éviter pendant la grossesse (fumé).'])
F('anchois', 'Anchois (filets à l’huile)', 'a few anchovy fillets on a small plate', 'poisson', 26000, '20 g (4 filets)', 20, [MED, ASI], False, True, False, [SM, PO], 'E:conserve', 'ALL', al=['poissons'], cr=['autres poissons (parvalbumine, avis allergologue)'], pr=PO_PR + ['Très salé : petite quantité ; hypertension ou maladie rénale : avis médical.'], cp=[])
F('truite', 'Truite', 'a baked rainbow trout fillet', 'poisson', 27014, '120 g', 120, [FRA, NOR], True, True, True, [PO, SM], 'E:pois', 'ALL', al=['poissons'], cr=['autres poissons (parvalbumine, avis allergologue)'], pr=PO_PR + ['Truite fumée : à éviter pendant la grossesse.'])
F('cabillaud', 'Cabillaud', 'a steamed cod fillet, white and flaky', 'poisson', 26025, '120 g', 120, [FRA, NOR, MED], False, True, False, [PO, SM, SU], 'E:pois', 'ALL', al=['poissons'], cr=['autres poissons (parvalbumine, avis allergologue)'], pr=PO_PR, cp=[])
F('lieu_noir', 'Lieu noir', 'a cooked pollock fillet', 'poisson', 26015, '120 g', 120, [FRA, NOR], True, True, False, [PO, SM, SU], 'E:pois', 'ALL', al=['poissons'], cr=['autres poissons (parvalbumine, avis allergologue)'], pr=PO_PR, cp=[])
F('merlan', 'Merlan', 'a steamed whiting fillet', 'poisson', 26022, '120 g', 120, [FRA], True, True, False, [PO, SM], 'I:merlan', 'ALL', al=['poissons'], cr=['autres poissons (parvalbumine, avis allergologue)'], pr=PO_PR, cp=[])
F('dorade', 'Dorade royale', 'a whole baked sea bream with lemon', 'poisson', 27031, '150 g', 150, [MED], True, True, False, [PO], 'E:pois', 'ALL', al=['poissons'], cr=['autres poissons (parvalbumine, avis allergologue)'], pr=PO_PR + ['Poisson prédateur (dorade) : grossesse et allaitement, au plus 150 g par semaine (ANSES).'], et=['JAYEDI18', 'ANSES_POISSONS'])
F('bar', 'Bar (loup)', 'a roasted sea bass fillet with crisp skin', 'poisson', 27030, '150 g', 150, [MED, FRA], True, True, False, [PO], 'E:pois', 'ALL', al=['poissons'], cr=['autres poissons (parvalbumine, avis allergologue)'], pr=PO_PR + ['Poisson prédateur (loup/bar) : grossesse et allaitement, au plus 150 g par semaine (ANSES).'], et=['JAYEDI18', 'ANSES_POISSONS'])
F('thon_naturel', 'Thon au naturel (conserve)', 'flaked tuna in a small ceramic dish', 'poisson', 26039, '100 g égoutté', 100, [MED, UNI], False, False, False, [SM], 'E:conserve', 'ALL', al=['poissons'], cr=['autres poissons (parvalbumine, avis allergologue)'], cp=[], pr=PO_PR + ['Thon (poisson prédateur) : grossesse, allaitement et enfants de moins de 3 ans, au plus 150 g par semaine (ANSES) ; à varier avec les petits poissons.'], et=['JAYEDI18', 'ANSES_POISSONS'], sg='Conserve : pratique et économique ; choisir au naturel.')

# ---------------- MOLLUSQUES ET CRUSTACÉS ----------------
F('moule', 'Moule', 'a bowl of steamed mussels', 'fruit_de_mer', 10013, '250 g avec coquilles (environ 100 g de chair)', 250, [FRA, NOR, MED], True, True, True, [PO, SM], 'I:moule', 'ALL', al=['mollusques'], cr=['autres mollusques et crustacés, acariens (tropomyosine)'], pr=['Allergène majeur (mollusques).', 'Toujours bien cuites ; jeter celles qui restent fermées.', 'Grossesse, immunodépression : jamais crues.'], gl='C', cl=[], et=['SANTE_GROSSESSE'])
F('crevette', 'Crevette cuite', 'a few pink cooked prawns', 'fruit_de_mer', 10007, '100 g décortiquées', 100, [ASI, LAT, MED, UNI], False, False, False, [PO, SM, SU], 'I:crevette', 'ALL', al=['crustaces'], cr=['acariens et mollusques (tropomyosine)'], cp=[], pr=['Allergène majeur (crustacés).', 'Grossesse : éviter les crustacés décortiqués vendus cuits (Santé.fr) ; les cuire soi-même.'], gl='C', cl=[], et=['SANTE_GROSSESSE'])
F('calamar', 'Calamar (encornet)', 'grilled squid rings on a plate', 'fruit_de_mer', 10037, '120 g', 120, [MED, ASI], False, True, False, [PO, SU], 'E:crust', 'ALL', al=['mollusques'], cr=['crustacés et acariens (tropomyosine)'], cp=[], pr=['Allergène majeur (mollusques).', 'Pas en beignets : cuisson simple (grillé, poêlé).'], gl='C', cl=[])
F('poulpe', 'Poulpe', 'a grilled octopus tentacle with olive oil', 'fruit_de_mer', 10079, '120 g', 120, [MED], False, True, False, [PO, SU], 'E:crust', 'ALL', al=['mollusques'], cr=['crustacés et acariens (tropomyosine)'], cp=[], pr=['Allergène majeur (mollusques).'], gl='C', cl=[])
F('saint_jacques', 'Noix de Saint-Jacques', 'three seared scallops', 'fruit_de_mer', 10004, '100 g', 100, [FRA], True, True, False, [PO, SU], 'I:stjacques', 'ALL', al=['mollusques'], cr=['crustacés et acariens (tropomyosine)'], cp=[], pr=['Allergène majeur (mollusques).', 'Grossesse : bien cuites.'], gl='C', cl=[], sais_note='surgelées toute l’année ; saison de pêche fraîche non documentée ici (aucun calendrier officiel consulté)')
F('palourde', 'Palourde (clam)', 'a small pan of steamed clams', 'fruit_de_mer', 10027, '250 g avec coquilles', 250, [MED, FRA, ASI], True, True, False, [PO], 'E:crust', 'ALL', al=['mollusques'], cr=['crustacés et acariens (tropomyosine)'], cp=[], pr=['Allergène majeur (mollusques).', 'Toujours bien cuites ; grossesse : jamais crues.'], gl='C', cl=[])

# ---------------- VIANDES ----------------
VR = ['Viande hors volaille : au plus 500 g par semaine (PNNS 2019) ; charcuterie au plus 150 g par semaine.', 'Maladie rénale chronique : apport protéique à fixer avec le néphrologue.', 'Grossesse : bien cuite à cœur (Santé.fr).']
F('poulet', 'Poulet (filet)', 'a pan-seared chicken breast, sliced', 'volaille', 36018, '120 g', 120, [UNI], True, True, True, [BO, SM, BI], 'E:volaille', 'ALL', cp=[], gl='C', cl=['proteines'], et=['PNNS'], pr=['Bien cuit à cœur (salmonelles, campylobacter).', 'Maladie rénale chronique : apport protéique à fixer avec le néphrologue.'], me="Protéine maigre ; aucune donnée sur la peau. La volaille n'est pas limitée par le PNNS, contrairement aux autres viandes.")
F('dinde', 'Dinde (escalope)', 'a sautéed turkey escalope', 'volaille', 36306, '120 g', 120, [UNI], True, True, True, [BO, SM, BI], 'E:volaille', 'ALL', cp=[], gl='C', cl=['proteines'], et=['PNNS'], pr=['Bien cuite à cœur.', 'Maladie rénale chronique : apport protéique à fixer avec le néphrologue.'], me="Protéine maigre ; aucune donnée sur la peau.")
F('lapin', 'Lapin', 'a braised rabbit leg with herbs', 'volaille', 34002, '120 g', 120, [FRA, MED], True, True, True, [BO, SM], 'I:lapin', 'ALL', cp=[], gl='C', cl=['proteines'], et=['PNNS'], pr=['Bien cuit à cœur.', 'Maladie rénale chronique : apport protéique à fixer avec le néphrologue.'], me="Viande maigre ; aucune donnée sur la peau.")
F('boeuf_maigre', 'Bœuf maigre (steak)', 'a grilled lean beef steak, sliced', 'viande', 6200, '100 g', 100, [FRA, LAT, UNI], True, True, True, [BO, SM, BI], 'I:rumsteck', 'ALL', cp=[], gl='C', cl=[], et=['IARC114', 'BOUVARD15', 'PNNS'], pr=VR, nu=['fer héminique'],
  me="Apporte fer et zinc bien absorbés ; aucune donnée sur la peau. Classée « probablement cancérogène » (groupe 2A) par le CIRC : quantité limitée.")
F('agneau', 'Agneau (gigot)', 'roasted leg of lamb slices with rosemary', 'viande', 21502, '100 g', 100, [ORI, MED, FRA], True, True, True, [BO, OR], 'E:viande3', 'ALL', cp=[], gl='C', cl=[], et=['IARC114', 'PNNS'], pr=VR, nu=['fer héminique'], me="Viande rouge ; aucune donnée sur la peau ; quantité limitée (PNNS).")
F('porc_filet', 'Porc (filet mignon)', 'a roasted pork tenderloin, sliced', 'viande', 28203, '100 g', 100, [FRA, ASI, NOR], True, True, True, [BO, SM], 'I:porc_filet', 'ALL', cp=[], gl='C', cl=[], et=['PNNS'], pr=VR, nu=['thiamine (vitamine B1)'], me="Viande maigre non transformée ; aucune donnée sur la peau ; comptée dans les 500 g de viande hors volaille par semaine.")

# ---------------- PRODUITS LAITIERS ET FROMAGES ----------------
LAIT_PR = ['Allergène majeur (lait).']
F('yaourt_grec', 'Yaourt à la grecque', 'a bowl of thick Greek yogurt', 'produit_laitier_fermente', 19860, '125 g', 125, [MED, ORI], False, True, True, [SM, BI], 'E:laitier', 'ALL', al=['lait'], cp=[], pr=LAIT_PR + ['Plus gras que le yaourt nature classique.'], gl='C', cl=['proteines'], et=['JUHL18', 'AGHASI19'])
F('fromage_blanc', 'Fromage blanc nature 3 %', 'a bowl of smooth fromage blanc', 'produit_laitier_fermente', 19646, '100 g', 100, [FRA], True, True, True, [SM, BI], 'E:laitier', 'ALL', al=['lait'], cp=[], pr=LAIT_PR, gl='C', cl=['proteines'], et=['JUHL18', 'AGHASI19'])
F('lait_demi_ecreme', 'Lait demi-écrémé', 'a glass of milk', 'produit_laitier', 19041, '200 mL', 200, [FRA, UNI], True, True, True, [SM, BI], 'E:laitier', 'ALL', al=['lait'], cp=[], pr=LAIT_PR + ['Acné : le lait est associé à l’acné dans des études d’observation (pas de preuve causale).'], gl='C', cl=[], et=['JUHL18', 'AGHASI19'])
F('chevre_frais', 'Fromage de chèvre frais (pasteurisé)', 'a fresh goat cheese log on a board', 'fromage', 12800, '30 g', 30, [FRA, MED], True, True, True, [SM, FR_, BI], 'E:fromage', 'ALL', al=['lait'], cp=[], pr=LAIT_PR + ['Grossesse : seulement au lait pasteurisé (Santé.fr : pas de fromages au lait cru).'], gl='C', cl=[], et=['SANTE_GROSSESSE'])
F('feta', 'Feta AOP', 'a block of feta with olive oil and oregano', 'fromage', 12061, '30 g', 30, [MED, ORI], False, True, True, [SM, FR_, OR], 'E:fromage', 'ALL', al=['lait'], cp=[], pr=LAIT_PR + ['Salée : petite quantité.', 'Grossesse : vérifier « lait pasteurisé » sur l’étiquette.'], gl='C', cl=[], et=['SANTE_GROSSESSE'])
F('parmesan', 'Parmesan', 'a wedge of Parmigiano with a few shavings', 'fromage', 12120, '15 g', 15, [MED], False, True, True, [SM, FR_], 'E:fromage', 'ALL', al=['lait'], cp=[], noclaim=True, pr=LAIT_PR + ['Fromage au lait cru : Santé.fr déconseille les fromages au lait cru pendant la grossesse.', 'Salé : petite quantité.'], gl='C', cl=[], et=['SANTE_GROSSESSE'])
F('comte', 'Comté', 'a wedge of Comté cheese', 'fromage', 12110, '30 g', 30, [FRA], True, True, True, [SM, FR_], 'E:fromage', 'ALL', al=['lait'], cp=[], pr=LAIT_PR + ['Fromage au lait cru : Santé.fr déconseille les fromages au lait cru pendant la grossesse.'], gl='C', cl=[], et=['SANTE_GROSSESSE'])
F('mozzarella', 'Mozzarella', 'a ball of fresh mozzarella torn open', 'fromage', 19590, '60 g', 60, [MED], False, True, True, [SM, FR_], 'E:fromage', 'ALL', al=['lait'], cp=[], pr=LAIT_PR, gl='C', cl=[])
F('ricotta', 'Ricotta', 'a bowl of fresh ricotta', 'fromage', 19585, '60 g', 60, [MED], False, True, True, [SM, FR_], 'E:fromage', 'ALL', al=['lait'], cp=[], pr=LAIT_PR, gl='C', cl=[])
F('brebis_pyrenees', 'Fromage de brebis des Pyrénées', 'a wedge of Pyrenean sheep cheese', 'fromage', 12747, '30 g', 30, [FRA], True, True, True, [SM, FR_], 'E:fromage', 'ALL', al=['lait'], cp=[], pr=LAIT_PR + ['Souvent au lait cru : pas pendant la grossesse (Santé.fr).'], gl='C', cl=[], et=['SANTE_GROSSESSE'])

# ---------------- ÉPICES, HERBES, AROMATES ----------------
EP = dict(cp=[], noclaim=True, gl='C', cl=[])
F('curcuma', 'Curcuma (poudre)', 'a small mound of bright turmeric powder', 'epice_herbe', 11089, '2 g (1 cuillère à café rase)', 2, [ASI, ORI, AFR], False, False, True, [SM, AS, OR, BI], 'E:epice', 'ALL', et=['VOLLONO19', 'ANSES_CURCUMA'], **EP,
  me="Épice de cuisine ; les effets cutanés étudiés portent sur la curcumine concentrée (compléments, gels), pas sur l'épice : aucune preuve pour l'aliment.",
  pr=['Les compléments de curcuma ne sont pas l’épice : l’ANSES a recensé des hépatites et des interactions (anticoagulants, anticancéreux, immunosuppresseurs) avec les compléments. En cuisine, aucune restriction connue.', 'Calculs biliaires : avis médical avant des quantités importantes.'])
F('gingembre', 'Gingembre (racine fraîche)', 'a knob of fresh ginger root, partly sliced', 'epice_herbe', 11074, '5 g', 5, [ASI, AFR, ORI, LAT], False, False, True, [SM, AS, OR, BI], 'E:epice', 'ALL', **EP, me="Aromate ; aucune donnée cutanée pour l'aliment.", pr=['Traitement anticoagulant : pas de compléments de gingembre sans avis ; en cuisine, quantités habituelles.'])
F('cannelle', 'Cannelle (poudre)', 'cinnamon sticks and a small mound of powder', 'epice_herbe', 11025, '1 g (une demi-cuillère à café)', 1, [ORI, FRA, NOR, ASI], False, False, True, [SM, OR, BI], 'E:epice', 'ALL', et=['EFSA_COUMARINE'], **EP, me="Épice ; aucune donnée cutanée.",
  pr=['La cannelle casse (la plus courante) contient de la coumarine : pas de grandes quantités chaque jour (EFSA 2008), surtout chez l’enfant ; la cannelle de Ceylan en contient beaucoup moins.'])
F('cumin', 'Cumin (graines)', 'cumin seeds in a small brass dish', 'epice_herbe', 11042, '2 g', 2, [ORI, ASI, LAT, AFR], False, False, True, [SM, OR, AS, BI], 'E:epice', 'ALL', **EP, me="Épice ; aucune donnée cutanée.")
F('paprika', 'Paprika doux', 'a small mound of sweet paprika', 'epice_herbe', 11049, '2 g', 2, [MED, ORI, UNI], False, True, True, [SM, OR, BI], 'E:epice', 'ALL', **EP, me="Épice ; aucune donnée cutanée.", pr=['Paprika fort ou piment : plat épicé, déclencheur de rougeurs cité par des patients atteints de rosacée.'])
F('poivre_noir', 'Poivre noir', 'black peppercorns and a small grinder', 'epice_herbe', 11015, '0,5 g', 0.5, [UNI], False, False, True, [SM], 'E:epice', 'ALL', **EP, me="Épice ; aucune donnée cutanée.")
F('piment', 'Piment frais', 'two small red chillies', 'epice_herbe', 20151, '5 g', 5, [ASI, LAT, AFR, ORI], False, True, True, [SM, AS, OR], 'E:epice', 'ALL', **EP, me="Condiment ; aucune donnée cutanée.", pr=['Plat épicé : déclencheur de rougeurs cité par 45 % des patients atteints de rosacée (enquête déclarative de la National Rosacea Society).'], et=['ROSACEA_SURVEY'])
F('cardamome', 'Cardamome', 'green cardamom pods', 'epice_herbe', 11075, '1 g', 1, [ASI, ORI, NOR], False, False, True, [AS, OR, BI], 'E:epice', 'ALL', **EP, me="Épice ; aucune donnée cutanée.")
F('safran', 'Safran', 'a pinch of saffron threads', 'epice_herbe', 11039, '0,05 g (une pincée)', 0.05, [MED, ORI, ASI], True, True, True, [SM, OR], 'E:epice', 'ALL', **EP, me="Épice ; aucune donnée cutanée.", pr=['Grossesse : pas de doses supérieures à l’usage culinaire (quelques pistils).'])
F('ail', 'Ail', 'a garlic bulb and a few cloves', 'epice_herbe', 11000, '5 g (1 gousse)', 5, [UNI], True, True, True, [SM, MP, BI], 'E:epice', 'A:ail', **EP, me="Aromate ; aucune donnée cutanée pour l'aliment.", pr=['Compléments d’ail et anticoagulants : avis médical ; en cuisine, quantités habituelles.'])
F('persil', 'Persil', 'a bunch of flat-leaf parsley', 'epice_herbe', 11014, '10 g (une poignée hachée)', 10, [FRA, MED, ORI], True, True, True, [SM, MP, BI], 'E:epice', 'T:herbes_aromatiques', **EP, me="Herbe aromatique ; en petite quantité, son apport reste modeste.", pr=['Très riche en vitamine K : sous AVK, garder une consommation stable (attention au taboulé très persillé).'])
F('coriandre', 'Coriandre fraîche', 'a bunch of fresh coriander', 'epice_herbe', 11094, '10 g', 10, [ASI, ORI, LAT, AFR], True, True, True, [SM, MP, AS, OR], 'E:epice', 'T:herbes_aromatiques', **EP, me="Herbe aromatique ; aucune donnée cutanée.")
F('menthe', 'Menthe fraîche', 'a sprig of fresh mint', 'epice_herbe', 11027, '5 g', 5, [ORI, MED, ASI], True, True, True, [SM, MP, OR], 'E:epice', 'T:herbes_aromatiques', **EP, me="Herbe aromatique ; aucune donnée cutanée.")
F('basilic', 'Basilic', 'a bunch of fresh basil leaves', 'epice_herbe', 11033, '5 g', 5, [MED, ASI], True, True, True, [SM, MP], 'E:epice', 'T:herbes_aromatiques', **EP, me="Herbe aromatique ; aucune donnée cutanée.")
F('aneth', 'Aneth', 'fresh dill fronds', 'epice_herbe', 11093, '5 g', 5, [NOR], True, True, True, [SM, MP], 'E:epice', 'T:herbes_aromatiques', **EP, me="Herbe aromatique ; aucune donnée cutanée.")
F('ciboulette', 'Ciboulette', 'a small bundle of chives', 'epice_herbe', 11003, '5 g', 5, [FRA, NOR, ASI], True, True, True, [SM, MP], 'E:epice', 'T:herbes_aromatiques', **EP, me="Herbe aromatique ; aucune donnée cutanée.")
F('thym', 'Thym', 'a few sprigs of fresh thyme', 'epice_herbe', 11070, '1 g', 1, [FRA, MED], True, True, True, [SM, MP], 'E:epice', 'T:herbes_aromatiques', **EP, me="Herbe aromatique ; aucune donnée cutanée.")
F('romarin', 'Romarin', 'two sprigs of fresh rosemary', 'epice_herbe', 11068, '1 g', 1, [MED, FRA], True, True, True, [SM, MP], 'E:epice', 'T:herbes_aromatiques', **EP, me="Herbe aromatique ; aucune donnée cutanée.")
F('origan', 'Origan séché', 'a small dish of dried oregano', 'epice_herbe', 11035, '1 g', 1, [MED, LAT], True, True, True, [SM, BI], 'E:epice', 'ALL', **EP, me="Herbe aromatique ; aucune donnée cutanée.")
F('vanille', 'Vanille (gousse)', 'two vanilla pods', 'epice_herbe', 11057, '1 gousse (2 g)', 2, [FRA, UNI], False, False, True, [SM, BI], 'E:epice', 'ALL', **EP, me="Arôme ; aucune donnée cutanée.")

# ---------------- FERMENTÉS ET DIVERS ----------------
F('choucroute', 'Choucroute (chou fermenté, sans garniture)', 'a small bowl of sauerkraut', 'legume', 25220, '150 g', 150, [FRA, NOR], True, True, True, [SM, BI, BO], 'E:leg', 'ALL', cp=[], gl='C', cl=['fruits_legumes'], et=['WASTYK21'], nu=['fibres', 'vitamine C', 'produit fermenté'],
  me="Chou fermenté ; un essai de 17 semaines (18 adultes par bras) riche en aliments fermentés a augmenté la diversité du microbiote et baissé des marqueurs d'inflammation (Wastyk 2021) : aucune donnée cutanée.", pr=['Salée : rincer ; hypertension ou maladie rénale : avis médical.', 'La choucroute cuite du commerce n’est plus « vivante » (ferments détruits).'])
F('miel', 'Miel', 'a spoon dripping golden honey', 'sucre', 31008, '10 g (1 cuillère à café)', 10, [UNI], True, True, True, [SM, MP, BI], 'E:epice', 'ALL', cp=[], noclaim=True, gl='D', cl=[], et=['PNNS'], me="Sucre : à limiter comme les autres produits sucrés (PNNS).", pr=['Jamais avant 1 an (botulisme infantile).', 'Diabète : compter comme du sucre.'])
F('sirop_erable', 'Sirop d’érable', 'a small jug of maple syrup', 'sucre', 31034, '10 g', 10, [NOR, UNI], False, False, True, [SM, BI], 'E:epice', 'ALL', cp=[], noclaim=True, gl='D', cl=[], et=['PNNS'], me="Sucre : à limiter comme les autres produits sucrés (PNNS).")

# ---------------- COMPLÉMENTS (lot 2) ----------------
F('rutabaga', 'Rutabaga', 'a waxed rutabaga and a few yellow cubes', 'legume', 20201, '150 g', 150, [NOR, FRA], True, True, True, [MP, BI], 'E:leg', 'NONE')
F('chou_rave', 'Chou-rave', 'a pale green kohlrabi with leaves', 'legume', 20065, '150 g', 150, [FRA, NOR, ASI], True, True, True, [MP, BI], 'E:leg', 'NONE')
F('courge_musquee', 'Courge musquée', 'a wedge of musk squash with deep orange flesh', 'legume', 20128, '200 g', 200, [FRA, MED, AFR, LAT], True, True, True, [MP, BI, SM], 'E:leg', 'A:courge')
F('haricot_beurre', 'Haricot beurre', 'a handful of yellow wax beans', 'legume', 20195, '150 g', 150, [FRA], True, True, True, [MP, BI, SU], 'E:leg', 'T:haricot_vert', fz=20203)
F('sucrine', 'Sucrine', 'two little gem lettuces, one halved', 'legume', 20288, '80 g', 80, [FRA, UNI], True, True, True, [SM, MP, BI], 'E:leg', 'T:salade')
F('laitue_romaine', 'Laitue romaine', 'a crisp romaine lettuce heart', 'legume', 20171, '80 g', 80, [MED, UNI], True, True, True, [SM, MP, BI], 'R:laitue', 'A:laitue')
F('chicoree_frisee', 'Chicorée frisée', 'a frisée lettuce with pale centre', 'legume', 20012, '80 g', 80, [FRA], True, True, True, [MP, SM, BI], 'E:leg', 'T:salade')
F('oignon_rouge', 'Oignon rouge', 'a red onion cut in half', 'legume', 20238, '50 g', 50, [MED, LAT, UNI], True, True, True, [SM, MP, BI], 'I:oignon', 'A:oignon', cp=[])
F('poivron_vert', 'Poivron vert', 'a green bell pepper and one halved', 'legume', 20085, '100 g', 100, [MED, LAT, AFR, ASI], True, True, True, [SM, MP, BI], 'R:poivron_vert', 'A:poivron', cr=['syndrome latex-fruits (poivron cité par Wagner 2002)'])
F('courge_spaghetti', 'Courge spaghetti', 'a halved spaghetti squash with golden strands', 'legume', 20143, '200 g cuite', 200, [FRA, UNI], True, True, True, [MP, BI], 'E:leg', 'A:courge')
F('taro', 'Taro', 'a hairy taro root and cooked cubes', 'feculent', 53201, '150 g cuit', 150, [ASI, AFR], False, False, False, [AS, OR], 'E:exo', 'ALL', cp=[], pr=['Toujours cuit (cristaux d’oxalate irritants à cru).'])
F('christophine', 'Christophine (chayote)', 'a pale green chayote squash', 'legume', 13177, '150 g cuite', 150, [LAT, AFR], False, False, False, [AS, OR], 'E:exo', 'ALL')
F('riz_sauvage', 'Riz sauvage', 'cooked black wild rice in a bowl', 'cereale_complete', 9111, '150 g cuit', 150, [LAT, UNI], False, False, True, [SM, BI], 'E:sec', 'ALL', gl='B')
F('lentille_blonde', 'Lentille blonde', 'blond lentils in a small bowl', 'legumineuse', 20588, '150 g cuites', 150, [FRA, ORI], True, True, True, [SM, BI, OR], 'E:sec', 'ALL')
F('farine_complete', 'Farine de blé complète (T150)', 'a small heap of wholemeal flour', 'cereale_complete', 9415, '30 g (dans une recette)', 30, [UNI], True, True, True, [SM, BI], 'E:sec', 'ALL', al=['cereales_gluten'], cp=[], noclaim=True, me="Ingrédient de recettes (pâtes, galettes, crêpes) ; remplace la farine blanche pour garder les fibres.")
F('pain_pita', 'Pain pita', 'two warm pita breads', 'feculent', 7180, '60 g (1 pita)', 60, [ORI, MED], False, True, True, [SM, OR], 'E:sec', 'ALL', al=['cereales_gluten'], cp=[], gl='C', cl=[])
F('eglefin', 'Églefin', 'a steamed haddock fillet', 'poisson', 26008, '120 g', 120, [NOR, FRA], False, True, False, [PO, SM, SU], 'E:pois', 'ALL', al=['poissons'], cr=['autres poissons (parvalbumine, avis allergologue)'], pr=PO_PR + ['Haddock (églefin fumé) : très salé et à éviter pendant la grossesse.'], cp=[])
F('lotte', 'Lotte (baudroie)', 'a pan-seared monkfish medallion', 'poisson', 26081, '120 g', 120, [FRA, MED], True, True, False, [PO], 'I:lotte', 'ALL', al=['poissons'], cr=['autres poissons (parvalbumine, avis allergologue)'], pr=PO_PR + ['Poisson prédateur (lotte) : grossesse et allaitement, au plus 150 g par semaine (ANSES).'], cp=[], et=['JAYEDI18', 'ANSES_POISSONS'])
F('rouget', 'Rouget-barbet', 'two small red mullet fillets', 'poisson', 26110, '120 g', 120, [MED, FRA], True, True, False, [PO], 'E:pois', 'ALL', al=['poissons'], cr=['autres poissons (parvalbumine, avis allergologue)'], pr=PO_PR)
F('tourteau', 'Tourteau (crabe cuit)', 'a cooked brown crab on ice', 'fruit_de_mer', 10025, '100 g de chair', 100, [FRA, NOR], True, True, False, [PO], 'I:tourteau', 'ALL', al=['crustaces'], cr=['acariens et mollusques (tropomyosine)'], cp=[], pr=['Allergène majeur (crustacés).', 'Grossesse : bien cuit, pas de crustacés décortiqués vendus cuits (Santé.fr).'], gl='C', cl=[], et=['SANTE_GROSSESSE'])
F('bulot', 'Bulot', 'a small bowl of cooked whelks', 'fruit_de_mer', 10020, '100 g de chair', 100, [FRA], True, True, False, [PO], 'E:crust', 'ALL', al=['mollusques'], cr=['crustacés et acariens (tropomyosine)'], cp=[], pr=['Allergène majeur (mollusques).'], gl='C', cl=[])
F('veau_escalope', 'Veau (escalope)', 'a thin veal escalope with lemon', 'viande', 6520, '100 g', 100, [FRA, MED], True, True, True, [BO, SM], 'I:veau', 'ALL', cp=[], gl='C', cl=[], et=['PNNS'], pr=VR,  me="Viande maigre ; aucune donnée sur la peau ; comptée dans les 500 g de viande hors volaille par semaine.")
F('yaourt_brebis', 'Yaourt au lait de brebis nature', 'a small glass jar of sheep milk yogurt', 'produit_laitier_fermente', 19554, '125 g', 125, [FRA, MED], True, True, True, [SM, BI], 'E:laitier', 'ALL', al=['lait'], cp=[], pr=LAIT_PR, gl='C', cl=['proteines'], et=['JUHL18', 'AGHASI19'])
F('boisson_amande', 'Boisson à l’amande non sucrée', 'a glass of almond milk and a few almonds', 'boisson', 18107, '200 mL', 200, [UNI], False, True, True, [SM, BI], 'E:laitier', 'ALL', al=['fruits_a_coque'], cp=[], gl='C', cl=[], pr=FAC + ['Pauvre en protéines et, non enrichie, en calcium : ne remplace pas le lait chez l’enfant.'])
F('tisane', 'Tisane (infusion de plantes)', 'a glass cup of herbal infusion with a sprig', 'boisson', 18022, '250 mL', 250, [UNI], True, True, True, [SM, BI], 'E:epice', 'ALL', cp=['hydratation'], noclaim=True, gl='C', cl=['hydratation_generale'], et=['PALMA15', 'AKDENIZ18'], me="Boisson sans sucre qui participe aux apports en eau ; l'eau n'aide la peau que si l'on boit peu (preuves faibles).",
  pr=['Rosacée : boissons chaudes citées comme déclencheur ; laisser tiédir.', 'Grossesse et traitement quotidien : certaines plantes sont déconseillées (réglisse, millepertuis…) ; avis du pharmacien.'])
F('the_noir', 'Thé noir (infusion)', 'a cup of black tea', 'boisson', 18154, '250 mL', 250, [UNI, ASI, ORI, NOR], False, False, True, [SM, BI, AS, OR], 'E:epice', 'ALL', cp=[], noclaim=True, gl='C', cl=['hydratation_generale'], et=['HURRELL99'], me="Boisson ; aucune donnée cutanée.", pr=['Réduit l’absorption du fer : à distance des repas en cas d’anémie ou de régime végétarien.', 'Contient de la caféine : grossesse, au plus l’équivalent de 3 tasses de café par jour au total (Santé.fr).'])
F('jus_orange', 'Jus d’orange pressé', 'a glass of freshly squeezed orange juice with half an orange', 'boisson', 2013, '150 mL (1 verre)', 150, [UNI], True, True, True, [SM, MP, BI], 'I:orange_jus', 'A:orange', cp=['rides_fermete'], gl='C', cl=[], et=['PNNS', 'PULLAR17'],
  me="Apporte la vitamine C de l'orange, mais sans ses fibres : le PNNS compte au plus un verre de jus par jour dans les fruits.", pr=['Au plus un verre par jour (PNNS) ; le fruit entier garde les fibres.', 'Diabète : avis médical.'])
F('moutarde', 'Moutarde', 'a small ceramic pot of Dijon mustard with a spoon', 'condiment', 11013, '5 g (1 cuillère à café)', 5, [FRA], True, True, True, [SM, BI], 'E:epice', 'ALL', al=['moutarde'], cp=[], noclaim=True, gl='C', cl=[], me="Condiment ; aucune donnée cutanée.", pr=['Allergène majeur (moutarde).', 'Salée : petite quantité.'])
F('sauce_soja', 'Sauce soja', 'a small dish of soy sauce', 'condiment', 11104, '10 mL (1 cuillère à soupe)', 10, [ASI], False, False, True, [SM, AS, BI], 'E:epice', 'ALL', al=['soja', 'cereales_gluten'], cp=[], noclaim=True, gl='C', cl=[], me="Condiment très salé ; aucune donnée cutanée.", pr=['Allergènes majeurs (soja, blé) ; il existe des versions sans blé (tamari, lire l’étiquette).', 'Très salée : petite quantité ; hypertension ou maladie rénale : avis médical.'])
F('harissa', 'Harissa', 'a small bowl of red harissa paste', 'condiment', 11112, '5 g', 5, [ORI, AFR], False, False, True, [SM, OR], 'E:epice', 'ALL', cp=[], noclaim=True, gl='C', cl=[], et=['ROSACEA_SURVEY'], me="Condiment pimenté ; aucune donnée cutanée.", pr=['Plat épicé : déclencheur de rougeurs cité par des patients atteints de rosacée.', 'Salée : petite quantité.'])
F('curry', 'Curry (poudre)', 'a small mound of golden curry powder', 'epice_herbe', 11005, '2 g', 2, [ASI, AFR], False, False, True, [SM, AS, OR, BI], 'E:epice', 'ALL', **EP, me="Mélange d'épices ; aucune donnée cutanée.", pr=['Souvent pimenté : plat épicé, déclencheur de rougeurs cité en cas de rosacée.', 'Certains mélanges contiennent de la moutarde ou du céleri : lire l’étiquette.'])
F('muscade', 'Noix de muscade', 'a whole nutmeg and a small grater', 'epice_herbe', 11048, '0,2 g (une pincée)', 0.2, [FRA, UNI], False, False, True, [SM, BI], 'E:epice', 'ALL', **EP, me="Épice ; aucune donnée cutanée.", pr=['Une pincée seulement : toxique à forte dose (quelques grammes).'])
F('graines_pavot', 'Graines de pavot', 'blue poppy seeds in a small dish', 'graine', 11061, '5 g', 5, [NOR, ORI], False, True, True, [SM, BI], 'E:noix', 'ALL', cp=[], noclaim=True, me="Graine décorative ; en petite quantité, apport modeste.", pr=['Petites quantités culinaires seulement.'])
F('huile_lin', 'Huile de lin', 'a small bottle of golden flaxseed oil', 'matiere_grasse', 17180, '5 g (1 cuillère à café)', 5, [NOR, FRA], True, True, True, [BI, SM], 'E:huile', 'ALL', cp=['hydratation', 'texture'], gl='C', cl=['acides_gras_omega3'], et=['NEUKAM11', 'DESPIRT09', 'PAN12'], nu=['ALA (oméga-3 végétal)'],
  me="Huile la plus riche en ALA ; deux petits essais avec de l'huile de lin en complément ont montré une peau un peu moins sèche et moins rugueuse.", pr=['Crue uniquement, au réfrigérateur après ouverture (rancit vite).', 'Les essais cutanés portent sur l’huile en complément (gélules ou dose fixe).'])
F('lait_coco', 'Lait de coco', 'a small bowl of coconut milk and half a coconut', 'matiere_grasse', 18041, '50 mL', 50, [ASI, AFR, LAT], False, False, True, [SM, AS, OR, BI], 'E:exo', 'ALL', cp=[], noclaim=True, gl='D', cl=[], et=['PNNS'], me="Riche en graisses saturées ; aucune donnée cutanée : à utiliser en petite quantité.", pr=['Riche en graisses saturées : petite quantité, ou version allégée.'])
F('capres', 'Câpres', 'a small dish of capers', 'condiment', 11040, '5 g', 5, [MED], False, True, False, [SM], 'E:epice', 'ALL', cp=[], noclaim=True, gl='C', cl=[], me="Condiment salé ; aucune donnée cutanée.", pr=['Au vinaigre : sulfites possibles selon le vinaigre, lire l’étiquette.', 'Salées : petite quantité.'])
F('tomate_sechee', 'Tomate séchée', 'sun-dried tomatoes in a small dish', 'legume', 20189, '20 g', 20, [MED], False, True, True, [SM, BI], 'E:leg2', 'ALL', cp=[], nu=['lycopène'], pr=['Souvent salée : petite quantité.'])
F('crabe_miettes', 'Crabe en miettes (conserve)', 'white crab meat flakes in a small dish', 'fruit_de_mer', 10005, '60 g', 60, [UNI, ASI], False, False, False, [SM], 'E:crust', 'ALL', al=['crustaces'], cr=['acariens et mollusques (tropomyosine)'], cp=[], pr=['Allergène majeur (crustacés).', 'Salé : petite quantité.'], gl='C', cl=[])
